### PR TITLE
OverlayTrigger with defaultShow does not position tooltip correctly #6619

### PR DESCRIPTION
**Pull request by Emanib**

### CODE REVIEW

**Comment by Emanib** [comment]
Fix issue  #6619 
In this issue, #6619 The default show for the tooltip in the overlay trigger is not visible.
Because triggerNodeRef.current is not passing in safeFindDOMNode

PART OF GTC OPEN SOURCE INTIATIVE

**Comment by kyletsang** [comment]
`safeFindDOMNode` is already called here:
https://github.com/react-bootstrap/react-bootstrap/blob/f1c4b24a5fc0a74747972abf6d7769bb782efac3/src/OverlayTrigger.tsx#L200

This is what sets `triggerNodeRef`. The underlying issue is likely that popper isn't repositioning once the ref is resolved.

**Comment by jquense** [comment]
we really need to switch to a callback ref probably?

**Comment by kyletsang** [comment]
Closed in favor of #6657

**Pull request closed without merging**
