### PR TITLE
Allow alignRight prop for SplitButton

### LINKED ISSUE #3531: SplitButton should allow alignRight prop
The SplitButton component should have the alignRight property.

Since SplitButton makes use of Dropdown.Menu, the alignRight property needs to be able to be passed from the SplitButton to Dropdown.Menu to control the alignment of the menu.

Currently, when using the SplitButton, you can change the direction of the drop down, but you can't change how that menu aligns with the button itself.

### PR DESCRIPTION
**Pull request by JB1905**
Closes #3531

### CODE REVIEW

**Comment by taion** [comment]
that's not quite right – the default passthrough to `<Dropdown>` will take care of this, as you can see in our example, i think we just need to add the prop type, at most

**Comment by bpas247** [comment]
@JB1905 Do you have plans to change this PR to simply add a new prop type? Or should we go ahead and close this PR?

**Comment by JB1905** [comment]
I have no plans to change this PR

**Comment by bpas247** [comment]
Okay then I'll be closing this for now :) please feel free to re-open this PR if you happen to change it in the future.

**Pull request closed without merging**
