### PR TITLE
[added] TabbedArea allows disabled tabs

### LINKED ISSUE #217: Can not disable a TabbedArea tab
One of the props on a Nav is "disabled". This prop should be usable on the TabbedArea tabs to disable tabs.

### PR DESCRIPTION
**Pull request by traviscooper**
Closes #217

### CODE REVIEW

**Comment by mtscout6** [comment]
For future reference you can use `git push --force` to replace the commits in an existing PR :wink:

**Comment by traviscooper** [comment]
:+1:

**Comment by mtscout6** [comment]
LGTM

Need one more set of eyes from one of the @react-bootstrap/collaborators

**Comment by aabenoja** [comment]
:shipit:

**Pull request merged**
