### PR TITLE
Added Style prop to MenuItem

### PR DESCRIPTION
**Pull request by RichardLitt**
I'm having some issues understanding the build process, so I've edited just the one file for now. What more do I need to make this PR a reality?

### CODE REVIEW

**Comment by dozoisch** [comment]
Can't you style it using css?

**Comment by RichardLitt** [comment]
Not using an inline style. I'd have to pull in a separate CSS sheet to override.

**Comment by AlexKVal** [comment]
This issue exists because
- it is possible to apply any additional `props` (including `style`) to the `<li>` [MenuItem.js#L53](https://github.com/react-bootstrap/react-bootstrap/blob/0904adc2aedf2c0c0c0f8ba00eefce426c3d2e2a/src/MenuItem.js#L53)
- but not to the inner `<a>` [MenuItem.js#L32](https://github.com/react-bootstrap/react-bootstrap/blob/0904adc2aedf2c0c0c0f8ba00eefce426c3d2e2a/src/MenuItem.js#L32)

It seems a solution has to be something like this:
```js
<a {...this.props} onClick={...
```

But it is not so straightforward and simple as for now.

**Comment by RichardLitt** [comment]
Exactly. What's stopping that from being the solution?

**Comment by mtscout6** [comment]
Stuff like this is difficult. The concern is consistency through the rest of the library. Generally we've been trying to put stuff like this on the parent element of the component. So, in this case it would need to be applied to the `<li>`, but that doesn't help you out. In the case where it's been getting applied to a child element within the same component then we've been prefixing the prop with that elements name. Granted this has been the approach we've been taking for `className`. We haven't really considered anything similar for `style`. The other issue with this implementation is that the `style` prop would be equally applied to the `<li>` and the `<a>`, which would be undesirable in many cases. I agree with @dozoisch in this case that you're better off applying custom CSS.

**Comment by RichardLitt** [comment]
Alright, I'll do that. Thanks for the explanation! Seems a bit odd, though.

**Pull request closed without merging**
