### PR TITLE
Add community resources and support page to docs

### LINKED ISSUE #783: Live help sessions?
I contacted @mtscout6 and he suggested posting this here as you guys do everything by open governance.

What do you think about setting up regularly-scheduled, live hangouts for helping react-bootstrap users work through integration issues?

The goal is to create an extra layer of support for users who otherwise might open up issues for questions that could be better solved by jumping into a short pair-programming / screenshare session.

It's the kind of thing we do with our students at [Thinkful](http://thinkful.com) and I'd be curious to see if it works outside our walls... We already hold sessions on React so it'd be easy to open those up to the broader react-bootstrap community.

The closest comparison to anything currently out there is IRC / Slack / Gitter. The difference is that live hangouts naturally enable pairing and code review.

Let me know what you think.

### PR DESCRIPTION
**Pull request by cmrnh**
Hi again @mtscout6 @mathieumg @AlexKVal and team —

I added a support page to the docs and links to Thinkful in `README` and `CONTRIBUTING` to close #783. Let me know what you think!

Also, in line with feedback from @mtscout6 [here](https://github.com/react-bootstrap/react-bootstrap/issues/783#issuecomment-108999315) and a few other folks — Thinkful will be formalizing our Code of Conduct when we roll out a broader update to Thinkful in the next couple of months (although so far we haven't run into any issues in the sessions). Stay tuned!

### CODE REVIEW

**Comment by mtscout6** [comment]
This looks great! Thanks for putting this together.

Need one more set of eyes by one of the @react-bootstrap/collaborators

**Comment by mtscout6** [comment]
Closes #783

**Comment by aabenoja** [comment]
:+1:

**Comment by AlexKVal** [comment]
Nice :+1:

**Pull request merged**
