### PR TITLE
turn off autoFocus for docs

### PR DESCRIPTION
**Pull request by jquense**
refixes #845

### CODE REVIEW

**Comment by taion** [comment]
This is going to be a merge conflict with #855, might be easier just to lump it in there?

**Comment by jquense** [comment]
yeah, if we are gonna get that merged soon sure

**Comment by taion** [comment]
Ideally let's get that merged today and cut a release... it's been too long.

**Comment by AlexKVal** [comment]
:+1:

**Comment by jquense** [comment]
great I will try and hit those last few points in an hour or so

**Comment by dozoisch** [comment]
we could do a doc release also for that if needed

**Comment by AlexKVal** [comment]
Do not forget to merge this before docs release :wink:

**Comment by jquense** [comment]
I just added this in #855 instead

**Pull request closed without merging**
