### PR TITLE
Adding more top space to SidePanel for better visibility

### PR DESCRIPTION
**Pull request by javascript-alex**
**Problem:**
Due to the "Black Lives Matter" banner at the top, the right hand Sidebar panel was partially cut off and not readable or clickable after scrolling down. Especially at the "Forms" menu. See Screenshot as well.
screenshot-sidepanel-before

**Solution:**
Adding a bit more space at the top to the Sidepanel solves the problem. See Screenshot below.
screenshot-sidepanel-after

Thank you very much for reviewing this and I hope this little fix is appreciated.

Cheers,
Alex

### CODE REVIEW

**Comment by taion** [comment]
Can you add a comment noting that this extra value is to accommodate the top banner?

**Comment by kyletsang** [comment]
Looks like this was fixed as part of #5316.

I can see the full side nav on latest docs at https://react-bootstrap.github.io.

**Comment by taion** [comment]
ah, nice. guess we don't need this, then. thanks!

**Comment by javascript-alex** [comment]
Great, thanks :)

**Pull request closed without merging**
