### PR TITLE
[added] noButton in Alert

### PR DESCRIPTION
**Pull request by jcazor**
Allow creating auto closeable alerts with no buttons.

### CODE REVIEW

**Comment by jquense** [comment]
LGTM, if there isn't some sort of a11y concern I am not thinking of...

**Comment by taion** [comment]
@jquense Do you like having the timer-based dismiss thing as part of React-Bootstrap? I'm half-tempted to just delete that part.

**Comment by jquense** [comment]
o yeah that's not upstream is it? If not then yeah I don't think we should support it, since its trivial to implement, and doesn't cause issues like needing to reset timers when the alter changes or something.

**Comment by taion** [comment]
TWBS3 has no timer support, just dismiss support: http://getbootstrap.com/javascript/#alerts

My personal inclination is to drop the timer support; it's not awful to have but I don't see a great reason to have it.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/1636 would deprecate `<Alert dismissAfter>` entirely.

**Comment by taion** [comment]
No longer relevant now that https://github.com/react-bootstrap/react-bootstrap/pull/1636 is merged, since we're killing `dismissAfter` entirely.

**Pull request closed without merging**
