### PR TITLE
Allows for large modals

### PR DESCRIPTION
**Pull request by crisward**
A minor adjustment to allow for large modals via 

```
      <Modal title="My Modal"  bsClass="modal-lg">
        <div className="modal-body">
           <p>Modal Body</p>
        </div>
        <div className="modal-footer">
          <Button onClick={@close}>Close</Button>
        </div>
      </Modal> 

```

### CODE REVIEW

**Comment by mtscout6** [comment]
Can you provide an example of this on the docs page?

**Comment by crisward** [comment]
I'll see what I can do tonight

**Comment by mtscout6** [comment]
Thanks!

**Comment by crisward** [comment]
I've added an example, hope that's ok.

**Comment by mtscout6** [comment]
I'm sorry to give you the run around. I didn't realize it at the time, but large and small modals are already supported. Just use the `bsSize="large"` prop. I tried it out on the current docs page where you can live edit the code examples, and it worked just fine with the current release.

**Pull request closed without merging**
