### PR TITLE
feat: change default Nav components to non ul/li

### PR DESCRIPTION
**Pull request by jquense**
BREAKING CHANGE: components no longer default to a list

### CODE REVIEW

**Comment by taion** [comment]
btw, with nesting `nav` in `nav` with `<Navbar>` and `<Nav>`, will anything bad happen?

**Comment by jquense** [comment]
o shoot does navbar render a nav? this should probably be a plain `div` then...

**Comment by taion** [comment]
by default yeah https://github.com/react-bootstrap/react-bootstrap/blob/84ef393827ba79c4b7ffba38ad733cdd5e661fea/src/Navbar.js#L120

**Comment by jquense** [comment]
we need to figure out why FF keeps failing in tests...

**Comment by jquense** [comment]
also fixes #3360

**Pull request merged**
