### PR TITLE
[changed] Use named exports in index files

### LINKED ISSUE #350: ES6 imports and exports are not completly valid for ES6
I'm using jspm to import modules the ES6 way. At first I tried this:

```
import {ListGroup, ListGroupItem} from 'react-bootstrap';
```

this resulted in ``undefined`` for both though. Instead I had to use this:

```
import ListGroup from 'react-bootstrap/ListGroup';
import ListGroupItem from 'react-bootstrap/ListGroupItem';
```

I may be getting this entirely wrong as I'm still learning all this, but I thought I'd point it out in case it's an issue on your side.

### PR DESCRIPTION
**Pull request by taion**
Fixes #350

### CODE REVIEW

**Comment by mtscout6** [comment]
LGTM

**Comment by taion** [comment]
Squashed in an update explicitly showing the ES6 import syntax on the "getting started" page.

**Comment by mtscout6** [comment]
Perfect I didn't think of those docs for this.

**Comment by taion** [comment]
Going to leave this up a bit longer in case anybody has thoughts as to whether requiring e.g.

```js
import * as ReactBootstrap from 'react-bootstrap';
import * as FormControls from 'react-bootstrap/lib/FormControls';
```

v. the current

```js
import ReactBootstrap from 'react-bootstrap';
import FormControls from 'react-bootstrap/lib/FormControls';
```

when using ES6 module syntax is objectionable.

**Comment by mtscout6** [comment]
Only other concern I just thought about https://github.com/react-bootstrap/react-bootstrap/issues/350#issuecomment-111728159

**Comment by jquense** [comment]
I don't think that is an big issue...I think the transpilations/umd build will handle that correctly, just like the es6 -> commonJs works correctly, there wouldn't be any other way to handle that. But i may just being hopeful.

**Comment by taion** [comment]
I expect this won't break users of the concatenated build. Checking real quick.

**Comment by taion** [comment]
The global `ReactBootstrap` variable is still a keyed object with the public components as keys.

`utils` and `FormControls` would have worked, except I messed up the re-exports in the merge. They'll work after I squash a fix.

**Comment by zerotacg** [comment]
I kind of feel like I set of an avalanche. I didn't mean to say the current way is wrong I merely was giving a possible workaround.
As for the fix. I'd vote for keeping the current default export along side the extra exports for compatibility.
In the long run I'd say it depends on how developers in general want to use the module syntax.
Is there an advantage of using

    import {Alert} from ...
    <Alert>...</Alert>

over

    import ReactBootstrap from ...
    <ReactBootstrap.Alert></ReactBootstrap.Alert>

well except from the length obviously? The shorter version sure looks sexy though

**Comment by taion** [comment]
The former is more semantically correct, due to some stuff w/potentially having static module structure. Note that the latter pattern remains possible, you'd just have to do

```js
import * as ReactBootstrap from 'react-bootstrap';
```

**Comment by taion** [comment]
AppVeyor failure is resolved by #826, I believe.

**Comment by mtscout6** [comment]
@zerotacg It's no avalanche, just healthy discussion as we all learn and progress.

@taion I'll merge master into v0.24.0-rc so that change is on this branch.

LGTM

**Comment by taion** [comment]
Okay, I'll merge for now, and we can revert if anybody comes back and objects.

**Comment by AlexKVal** [comment]
```js
import {Alert} from ...
<Alert>...</Alert>
```
> ...is more semantically correct

:+1:

**Pull request merged**
