### PR TITLE
Finding nested components in Modal through Refs.

### PR DESCRIPTION
**Pull request by imcharsi**
Hi.

At first, My English is poor. I'm sorry about that.

In current implementation, it looks like that below codes are not worked.

```
    var Xxx = React.createClass({
      render:function(){
        return (
          <div>
            <Modal show bsSize='small' onHide={noOp} ref="modal">
              <Modal.Header ref="header">
                <Modal.Title ref="title">
                  <strong ref="titleMsg">{titleMsg}</strong>
                </Modal.Title>
                <strong ref="headerMsg">{headerMsg}</strong>
              </Modal.Header>
              <Modal.Body ref="body">
                <strong ref="bodyMsg">{bodyMsg}</strong>
              </Modal.Body>
              <Modal.Footer ref="footer">
                <strong ref="footerMsg">{footerMsg}</strong>
              </Modal.Footer>
            </Modal>
          </div>
        );
      }
    });
    let instance = render(
      <Xxx/>
    , mountPoint);

    assert.ok(instance.refs.modal.refs.header.refs.headerMsg.props.children.match(headerMsg));
```

What I want to do was to click some buttons in Modal at testing, so I tried this pull request.

Review please.

### CODE REVIEW

**Comment by jquense** [comment]
Hi there thanks for the PR. I am a bit confused what you are trying to accomplish though, refs already work and your PR seems to make accessing refs harder

**Comment by imcharsi** [comment]
Hi.

Thanks for reply.

After I clear npm cache and reinstall react-bootstrap ver 0.24.2, I tried again that problems.

As I thought previously, I couldn't find nested components in `Modal`(I said `Modal`).

What I want to do is to run test codes like below.

```
React.addons.TestUtils.Simulate.click(xxx.refs.modal.refs.footer.refs.someButton.getDOMNode());
```

Was I something wrong?

If there are any way to find nested component in `Modal`, please tell me.

below are example codes that I tested.

`bundle.js`

```
var React = require("react/addons"); // 0.13.3 orig
global.React = React;
var ReactBootstrap = require("react-bootstrap"); // 0.24.2 orig
global.ReactBootstrap = ReactBootstrap;
```

```
browserify bundle.js -o bundle.out.js
```

`index.html`

```
<!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script type="text/javascript" src="JSXTransformer.js"></script>
    <script type="text/javascript" src="bundle.out.js"></script>
    <link rel="stylesheet" href=".../bootstrap.css">
</head>

<body>
    <script type="text/jsx" src="main.jsx"></script>
</body>

</html>
```


main.jsx

```
    var Xxx = React.createClass({
      onClick:function(){
        console.info("click");
      },
      render:function(){
      var titleMsg="titleMsg";
      var headerMsg="headerMsg";
      var bodyMsg="bodyMsg";
      var footerMsg="footerMsg";

        return (
          <div>
            <ReactBootstrap.Modal show={true} bsSize='small' onHide={function(){}} ref="modal">
              <ReactBootstrap.Modal.Header ref="header">
                <ReactBootstrap.Modal.Title ref="title">
                  <strong ref="titleMsg">{titleMsg}</strong>
                </ReactBootstrap.Modal.Title>
                <strong ref="headerMsg">{headerMsg}</strong>
              </ReactBootstrap.Modal.Header>
              <ReactBootstrap.Modal.Body ref="body">
                <strong ref="bodyMsg">{bodyMsg}</strong>
              </ReactBootstrap.Modal.Body>
              <ReactBootstrap.Modal.Footer ref="footer">
                <strong ref="footerMsg">{footerMsg}</strong>
                <p ref="p" onClick={this.onClick}>p</p>
              </ReactBootstrap.Modal.Footer>
            </ReactBootstrap.Modal>
          </div>
        );
      }
    });
    var xxx = React.render(
      <Xxx/>, document.body);
```

in browser console

```
React.addons.TestUtils.Simulate.click(xxx.refs.modal.refs.footer.refs.p.getDOMNode());
```

**Comment by jquense** [comment]
Ya that's not quick how refs work, they are all on the component that declares them so try: `xxx.refs.p`

**Comment by imcharsi** [comment]
Hi.

Thanks for reply.

As you said, It is possible.

I'm sorry to bother you and thanks to let me know it.

I'll close this PR.

**Pull request closed without merging**
