### PR TITLE
[added] Allow overriding element in FormControls.Static

### PR DESCRIPTION
**Pull request by egauci**
Addresses issue #1559

### CODE REVIEW

**Comment by taion** [comment]
Please fix the linting.

**Comment by egauci** [comment]
Sorry about that. I have problems linting in this project. If I run 'npm run lint' I get "1950 problems". It seems to need a different version of eslint, as the errors are all related to incompatibility with .eslintrc.

**Comment by taion** [comment]
Thanks! LGTM.

**Comment by jquense** [comment]
:shipit:

**Pull request merged**
