### PR TITLE
#2449 removed h3 from Popover

### PR DESCRIPTION
**Pull request by jshaker**

### CODE REVIEW

**Comment by skwon-mdsol** [comment]
Not sure if this is the solution to the popover markup, nor was it ever decided by the owners to do such a thing. This could potentially be  abreaking change.

**Comment by taion** [comment]
Yeah, this isn't safe – this changes what gets rendered.

**Comment by skwon-mdsol** [comment]
I think this one should be closed.

**Comment by taion** [comment]
Okay, closing this for now. I think the right way to go about things here is to have a separate `<Popover.Title>` component per https://github.com/react-bootstrap/react-bootstrap/issues/2449#issuecomment-277114258.

**Pull request closed without merging**
