### PR TITLE
Convert OverlayTrigger to an arrow function to fix type issues

### LINKED ISSUE #6708: OverlayTrigger namespace propTypes does not match the OverlayTriggerProps interface
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

In OverlayTrigger.d.ts, the namespace OverlayTrigger declaration contains a var propTypes that does not match the OverlayTriggerProps declaration in the same file.  The optional properties are declared as required in the namespace.  This leads to type confusion in tools like the WebStorm IDE.

### Expected behavior

The optional properties should be declared optional in the propTypes declaration.

### To Reproduce

_No response_

### Reproducible Example

https://codesandbox.io/s/beautiful-dream-lwcm96

### Screenshots

_No response_

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.9.0

### What version of Bootstrap are you using?

5.3.2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snstanton**
Fixes #6708

### CODE REVIEW

**Comment by kyletsang** [comment]
OverlayTrigger is the only component that exports the propTypes in the d.ts file.  Using a `React.FC` type here stops that from being emitted.  Perhaps we should use that as well?

**Comment by snstanton** [comment]
I've added the React.FC type and fixed up various type mismatches between the propTypes and the interface.

**Comment by kyletsang** [comment]
Before:
```
import PropTypes from 'prop-types';
import * as React from 'react';
import { OverlayChildren, OverlayProps } from './Overlay';
export type OverlayTriggerType = 'hover' | 'click' | 'focus';
export type OverlayDelay = number | {
    show: number;
    hide: number;
};
export type OverlayInjectedProps = {
    onFocus?: (...args: any[]) => any;
};
export type OverlayTriggerRenderProps = OverlayInjectedProps & {
    ref: React.Ref<any>;
};
export interface OverlayTriggerProps extends Omit<OverlayProps, 'children' | 'target'> {
    children: React.ReactElement | ((props: OverlayTriggerRenderProps) => React.ReactNode);
    trigger?: OverlayTriggerType | OverlayTriggerType[];
    delay?: OverlayDelay;
    show?: boolean;
    defaultShow?: boolean;
    onToggle?: (nextShow: boolean) => void;
    flip?: boolean;
    overlay: OverlayChildren;
    target?: never;
    onHide?: never;
}
declare function OverlayTrigger({ trigger, overlay, children, popperConfig, show: propsShow, defaultShow, onToggle, delay: propsDelay, placement, flip, ...props }: OverlayTriggerProps): JSX.Element;
declare namespace OverlayTrigger {
    var propTypes: {
        children: PropTypes.Validator<NonNullable<NonNullable<((...args: any[]) => any) | PropTypes.ReactElementLike | null | undefined>>>;
        /**
         * Specify which action or actions trigger Overlay visibility
         *
         * The `click` trigger ignores the configured `delay`.
         *
         * @type {'hover' | 'click' |'focus' | Array<'hover' | 'click' |'focus'>}
         */
        trigger: PropTypes.Requireable<NonNullable<string | (string | null | undefined)[] | null | undefined>>;
        /**
         * A millisecond delay amount to show and hide the Overlay once triggered
         */
        delay: PropTypes.Requireable<NonNullable<number | PropTypes.InferProps<{
            show: PropTypes.Requireable<number>;
            hide: PropTypes.Requireable<number>;
        }> | null | undefined>>;
        /**
         * The visibility of the Overlay. `show` is a _controlled_ prop so should be paired
         * with `onToggle` to avoid breaking user interactions.
         *
         * Manually toggling `show` does **not** wait for `delay` to change the visibility.
         *
         * @controllable onToggle
         */
        show: PropTypes.Requireable<boolean>;
        /**
         * The initial visibility state of the Overlay.
         */
        defaultShow: PropTypes.Requireable<boolean>;
        /**
         * A callback that fires when the user triggers a change in tooltip visibility.
         *
         * `onToggle` is called with the desired next `show`, and generally should be passed
         * back to the `show` prop. `onToggle` fires _after_ the configured `delay`
         *
         * @controllable `show`
         */
        onToggle: PropTypes.Requireable<(...args: any[]) => any>;
        /**
          The initial flip state of the Overlay.
         */
        flip: PropTypes.Requireable<boolean>;
        /**
         * An element or text to overlay next to the target.
         */
        overlay: PropTypes.Requireable<NonNullable<((...args: any[]) => any) | PropTypes.ReactElementLike | null | undefined>>;
        /**
         * A Popper.js config object passed to the the underlying popper instance.
         */
        popperConfig: PropTypes.Requireable<object>;
        /**
         * @private
         */
        target: PropTypes.Requireable<null>;
        /**
         * @private
         */
        onHide: PropTypes.Requireable<null>;
        /**
         * The placement of the Overlay in relation to it's `target`.
         */
        placement: PropTypes.Requireable<string>;
    };
}
export default OverlayTrigger;
```

After:
```
import * as React from 'react';
import { OverlayChildren, OverlayProps } from './Overlay';
import { Placement } from './types';
export type OverlayTriggerType = 'hover' | 'click' | 'focus';
export type OverlayDelay = number | {
    show: number;
    hide: number;
};
export type OverlayInjectedProps = {
    onFocus?: (...args: any[]) => any;
};
export type OverlayTriggerRenderProps = OverlayInjectedProps & {
    ref: React.Ref<any>;
};
export interface OverlayTriggerProps extends Omit<OverlayProps, 'children' | 'target'> {
    children: React.ReactElement | ((props: OverlayTriggerRenderProps) => React.ReactNode);
    trigger?: OverlayTriggerType | OverlayTriggerType[];
    delay?: OverlayDelay;
    show?: boolean;
    defaultShow?: boolean;
    onToggle?: (nextShow: boolean) => void;
    flip?: boolean;
    overlay: OverlayChildren;
    target?: never;
    onHide?: never;
    placement?: Placement;
}
declare const OverlayTrigger: React.FC<OverlayTriggerProps>;
export default OverlayTrigger;

```

**Review by kyletsang — APPROVED** [review]

**Comment by kyletsang** [comment]
Thanks!

**Pull request merged**
