### PR TITLE
[added] `createSelectedEvent` for consistent onSelect handling

### PR DESCRIPTION
**Pull request by mtscout6**
Related to #419 

This is the event that I have started using on the dropdown-revisited branch. Thought I'd pull the event from that branch in hopes that it may help with the events in #786

### CODE REVIEW

**Comment by taion** [comment]
I haven't had time to read through the related PR, but this implementation seems to be a lot more general than just handling "select" events.

**Comment by mtscout6** [comment]
This doesn't go and update any of the select events, it's just the event that would get passed in as described in https://github.com/react-bootstrap/react-bootstrap/issues/419#issuecomment-95956673.

I have already been using it in the dropdown-revisited branch and felt that @roadmanfong would benefit from it in #786

Example usage from dropdown-revisited:

- https://github.com/react-bootstrap/react-bootstrap/blob/dropdown-revisited/src/revisited/MenuItem.js#L23-L27
- https://github.com/react-bootstrap/react-bootstrap/blob/dropdown-revisited/src/revisited/DropdownButton.js#L77-L83

**Comment by mtscout6** [comment]
@taion Did I answer your question completely or did I miss something?

**Comment by taion** [comment]
Yes - question answered. Thanks.

**Comment by aabenoja** [comment]
:+1: LGTM

**Pull request merged**
