### PR TITLE
v5: Update Badge classes

### PR DESCRIPTION
**Pull request by thakkaryash94**
[ x ] Change .badge-variant class to .bg-variant
[ x ] Change .badge-pill class to .rounded-pill

Link: https://github.com/react-bootstrap/react-bootstrap/projects/2#card-42008293

New request from: https://github.com/react-bootstrap/react-bootstrap/pull/5345

### CODE REVIEW

**Comment by kyletsang** [comment]
Since all of these badge changes are now using util classes (border, bg color, text color), I'm thinking we should address this after #5373 is done.

@bpas247 what do you think?

**Comment by bpas247** [comment]
> Since all of these badge changes are now using util classes (border, bg color, text color), I'm thinking we should address this after #5373 is done.

Hmm, that's a tough call since that PR isn't going to be done for awhile 🤔 not sure if I want this to be blocked for that long.

Maybe we could merge this (pending approval) and we'll just rebase in #5373 accordingly?

Worst-case scenario some (or all) of the work that's done here will get deprecated later on 😛

**Comment by jquense** [comment]
ya lets merge this in, if we have larger changes that affect this later no big deal 👍

**Comment by thakkaryash94** [comment]
Thank you everyone for your support

**Comment by bpas247** [comment]
Absolutely 😄 thank you for contributing!

**Pull request merged**
