### PR TITLE
Set the disabled css class so that the text is greyed out.

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by jquense** [comment]
is this a feature from bootstrap? could you provide more context please?

**Comment by tannewt** [comment]
I think you could say that. This change makes the inner text of the dropdown match this less rule from Bootstrap: https://github.com/twbs/bootstrap/blob/master/less/navbar.less#L434

**Comment by taion** [comment]
Does this properly prevent the `Dropdown` button from being clicked?

**Comment by tannewt** [comment]
The click is already correctly prevented. This change only affects the appearance so that it looks disabled.

**Comment by taion** [comment]
Ah. Cool. LGTM. Need +1 reviewer.

**Comment by jquense** [comment]
I am a bit concerned that this is too implementation specific to go one the general Dropdown. would this present annoying styling resets for custom menus/toggles? Would it make more sense for the DropdownButton(s) to set it?

**Comment by taion** [comment]
Wouldn't that only be the case if they've defined a `.disabled` rule that would apply? Maybe I'm misunderstanding.

**Comment by taion** [comment]
@jquense ping

**Comment by AlexKVal** [comment]
Actually this is the fix for undiscovered, till now, bug.
@tannewt could you please add `[fixed]` into the beginning of your commit header ?
(it is then will be reflected in the [Changelog](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md))

Without this fix:
not-fixed

--
And with this fix:
fixed

and
fixed-neg

**Comment by tannewt** [comment]
@AlexKVal Done.

**Comment by AlexKVal** [comment]
I presume we cannot merge it yet because of @jquense concern.
Will wait his comments on this.
:cherries:

**Comment by jquense** [comment]
I think my concern as abated for now. LGTM

**Comment by AlexKVal** [comment]
@tannewt thank you for your contribution :cherries:

**Comment by tannewt** [comment]
Np! Happy to help.

**Pull request merged**
