### PR TITLE
Add pre-publish script call, rename cjs/ -> lib/

### PR DESCRIPTION
**Pull request by mtscout6**
Addresses concerns like #325, #218, and any others like them that I have
missed. In particular this is the fix for an automated setup as
mentioned in #292.

__NOTE THIS IS A BREAKING CHANGE__, however the long term benefits outweigh the cost of the change IMHO.

Adds `grunt release:<major|minor|patch|custom-version>` command which will update the package version, commit, git tag, npm publish, bower repo update, and docs repo update.

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
What's the rationale for the folder rename to lib?  Can we get the same npm deploy advantage with the existing cjs dir?

**Comment by mtscout6** [comment]
I renamed it to lib for two main reasons. First, it's the more common convention for node modules, trivial i agree. The second is for consistency between the cjs and amd approaches. Keeping the two approaches similar will allow downstream users an easier path to switch between amd and commonjs should they decide to do so. Take note that I updated the amd approach and documentation to follow suite.

While yes we can forego the name change and still gain the benefit of an npm deploy, but I don't feel that appropriately sets up this project for the future.

**Comment by mtscout6** [comment]
What's the sentiment on all this? react-bootstrap 0.13.0 is still broken on npm. Also I didn't even realize that 0.12.0 is also broken on npm. This is making it difficult to upgrade and get the latest bug fixes.

**Comment by mtscout6** [comment]
I also failed to mention earlier that this change will allow you to work with [npm link](https://docs.npmjs.com/cli/link)

**Comment by trentgrover-wf** [comment]
I hesitate to change this but for wholly selfish reasons:

I have a private fork of this library that includes a Dart wrapper so these components can be used from Dart, but Dart requires that all of its exposed code live in the `lib` directory.  If this react-bootstrap started using the `lib` directly, I'd have to find some workaround on my fork for managing the Dart stuff (but, of course, that's my problem, not yours).

Anybody else going to weigh in?

**Comment by mathieumg** [comment]
I don't really mind in this case, but I've also noticed that most of the projects go `/lib`, hence it is the approach I've also taken with my projects. That being said, if there is to be only one folder for the core files (and `/lib` isn't retained) I think it should be something that is agnostic to the module format, as opposed to `/cjs`. Just my two cents!

**Comment by mtscout6** [comment]
The question I have now is what to do about bower? I don't like having the separate repo, but I also don't like committing a distributable. Thoughts?

**Comment by mtscout6** [comment]
From what I can tell about bower there really is no better way than to commit the compiled output. So, keeping that additional repo is still necessary. I added a release task that will do the work of tagging, building and pushing to npm, bower repo, and docs repo in one swoop.

**Comment by mtscout6** [comment]
@trentgrover-wf Regarding your concern about using with Dart, could we do something similar to how we are handling bower now?

**Comment by mtscout6** [comment]
@mathieumg There's some changelog generation for you :smile: I'm still testing it locally a little bit, but I should wrap it up by tomorrow.

**Comment by mathieumg** [comment]
Awesome! I like the approach too. :+1:

**Comment by trentgrover-wf** [comment]
@mtscout6 you're doing all the heavy lifting for maintaining this library at the moment so don't worry about the dart issue when moving forward with this.  It's perfectly reasonable to expose the dart wrapper via a separate repo.  Maybe I'll get around to providing that code at some point for open-source use.

**Pull request merged**
