### PR TITLE
Use react-overlays for Modal

### PR DESCRIPTION
**Pull request by jquense**
Cut the modal over to use React-overlays

### CODE REVIEW

**Comment by taion** [comment]
I think `propTypes` should merge in `BaseModal.propTypes`... or at least point users toward base modal anyway.

**Comment by taion** [comment]
@jquense Do you have time to rebase this PR?

**Comment by jquense** [comment]
thar ya go!

**Comment by taion** [comment]
Why do you drop the composed-in `propTypes` on `Modal`?

**Comment by taion** [comment]
Thanks!

**Comment by jquense** [comment]
not intentional! will fix

**Comment by jquense** [comment]
:shipit:

**Comment by taion** [comment]
Okay, gonna squash into your commit then.

**Pull request merged**
