### PR TITLE
Do not ignore `offsetParent` in jQuery mode of `domUtils.getPosition`

### PR DESCRIPTION
**Pull request by Morhaus**

### CODE REVIEW

**Comment by taion** [comment]
LGTM. Need 1 more reviewer

**Comment by jquense** [comment]
vaguely unrelated why do we even have the jquery branch? also doesn't jquery's position use offsetParent or is the param here not actually an offsetParent?

**Comment by taion** [comment]
jQuery branch for IE8 compat

Explicit offsetParent there is actually only ever the container node for overlays, i.e. not actually the offset parent.

**Comment by AlexKVal** [comment]
It seems the fix for better IE8 support :+1: 
LGTM

**Pull request merged**
