### PR TITLE
fixup! Fix a few docs display glitches

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
Addresses https://github.com/react-bootstrap/react-bootstrap/pull/855#issuecomment-117283153

**Comment by jquense** [comment]
LGTM

**Comment by taion** [comment]
Wait don't merge yet, more more little thing to fix

**Comment by taion** [comment]
Go ahead and merge/rebase/fixup/whatever #855 once you've merged these changes, if you're okay with them.

**Pull request merged**
