### PR TITLE
Added missing exports.

### PR DESCRIPTION
**Pull request by VibhorJaiswal**
fixes:  #6226

### CODE REVIEW

**Review by golota60 — APPROVED** [review]
lgtm!

**Comment by VibhorJaiswal** [comment]
I have also converted ModalBody, ModalFooter, ModalHeader and ModalTitle to rtl.

**Comment by golota60** [comment]
@VibhorJaiswal Nice! 👍  Could you make a separate PR for testing-related changes? 
It'll make it easier to code review & merge those

**Comment by VibhorJaiswal** [comment]
@golota60 okay.

**Comment by kyletsang** [comment]
We don't need to expose ModalContext in the index.   Consumers don't need to use this

**Review by kyletsang — APPROVED** [review]

**Comment by kyletsang** [comment]
Thanks

**Pull request merged**
