### PR TITLE
[fixed] It is possible to merge OverlayMixin components

### LINKED ISSUE #527: How can I merge overlay mixin components?
Excuse me, I want your help.

I don't know that How it render the tooltip when a user hovers button which is a trigger for modal.

```html
<OverlayTrigger placement="bottom" overlay={<Tooltip>test1</Tooltip>}>
  <Button bsStyle="default">test1</Button>
</OverlayTrigger>
<OverlayTrigger placement="bottom" overlay={<Tooltip>test2</Tooltip>}>
  <ModalTrigger modal={<TestModal model={this.props.model}/>}>
    <Button bsStyle="default">test2</Button>
  </ModalTrigger>
</OverlayTrigger>
```

In this case, When I hovers "test1" button, It will render "test1" tooltip.
But, when I hovers "test2" button, It won't render "test2" tooltip.

Should I create a custom trigger?

```html
<OverlayTrigger placement="bottom" overlay={<Tooltip>test1</Tooltip>}>
  <Button bsStyle="default">test1</Button>
</OverlayTrigger>
<OverlayAndModalTrigger
  placement="bottom"
  overlay={<Tooltip>test2</Tooltip>}
  modal={<TestModal model={this.props.model}/>}>
</OverlayAndModalTrigger>
```

Please tell me if I can do other methods.

### PR DESCRIPTION
**Pull request by teloo**
I fixed #527.

### CODE REVIEW

**Comment by mtscout6** [comment]
LGTM, thanks for the added tests.

Need another sign-off by one of the @react-bootstrap/collaborators

**Comment by AlexKVal** [comment]
It seems this PR would close some issues.
A lot of work has been done :+1: :sparkle: :sparkles: 

`tests and lint` are green
`consoles` in browsers are clean

**Comment by teloo** [comment]
My pleasure. :smile:

**Comment by dozoisch** [comment]
Looks good thankd

**Pull request merged**
