### PR TITLE
#2613 added defaultOpen as a prop for DropdownButton

### PR DESCRIPTION
**Pull request by jshaker**

### CODE REVIEW

**Comment by taion** [comment]
You don't need to do this – just add it to propTypes for Dropdown.

**Comment by jshaker** [comment]
#2613 mentions adding it to DropdownButton though

Also, it seems Dropdown is already aware of the defaultOpen prop? 
Line 484:
https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownSpec.js

**Comment by taion** [comment]
The `splitComponentProps` looks explicitly at `propTypes` and will do the right thing. `<Dropdown>` knows about `defaultOpen`, yes, but it doesn't have it listed under `propTypes`.

**Comment by taion** [comment]
I added `defaultOpen` in #2702. Thanks!

**Pull request closed without merging**
