### PR TITLE
#200 issue add affix doc 

### PR DESCRIPTION
**Pull request by roderickwang**
#200 issue add affix doc

### CODE REVIEW

**Comment by taion** [comment]
Is this the only thing we need? I thought there were some functionality issues with `Affix` - are there actually not?

**Comment by roderickwang** [comment]
I think there actually are.I'll fix them when i am free.

**Comment by AlexKVal** [comment]
Hi @roderickwang :smile: 
You don't have to re-create every time new fixed PRs :wink: 
You can just `git push --force` them with your new changes every time
and as many time as you need :sparkle: 
I hope it will help you
:cherries:

**Comment by AlexKVal** [comment]
And of course you always can check linting locally to not wait for `TravisCI`
by this command:
```
$ npm run lint
```
and then all together: linting, tests and building by the
```
$ npm run test
```
:cherries:

**Comment by roderickwang** [comment]
@AlexKVal thanks,i'll notice that.

**Comment by taion** [comment]
@roderickwang Any update on fixing `Affix`? I'd prefer not to add documentation for a buggy component, because it wouldn't be suitable for general use.

**Comment by KabirKang** [comment]
Does this mean the component is suitable for general use now?

**Comment by grydstedt** [comment]
Anyone working on the Affix component at the moment?

**Comment by taion** [comment]
Not as far as I know.

**Comment by taion** [comment]
I'm going to close this PR for now. We'd prefer to merge a PR that also fixes the `Affix` implementation, rather than just documenting a component that's not really suitable for usage in its current state.

**Pull request closed without merging**
