### PR TITLE
Check for hover timeout before cancelling it

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by jquense** [comment]
why?

**Comment by taion** [comment]
We do it https://github.com/taion/react-bootstrap/blob/OverlayTrigger-clearTimeout/src/OverlayTrigger.js#L237 and https://github.com/taion/react-bootstrap/blob/OverlayTrigger-clearTimeout/src/OverlayTrigger.js#L262.

I dunno - think it's clearer not to do this check at all?

**Comment by jquense** [comment]
Ahh, I see consistency. I'm not sure I've never checked for a timeout before trying to clear it...I defer to you on that one.

**Comment by taion** [comment]
Actually forget it, that check is because we need to do something different in the case that the timeout is set.

**Pull request closed without merging**
