### PR TITLE
add unstyled SplitButton to docs #btn-dropdowns-split

### PR DESCRIPTION
**Pull request by sillyslux**
I was searching for an unstyled SplitButtonDropdown and since it already seems to be supported, i think it should be reflected in the documentation.

### CODE REVIEW

**Comment by taion** [comment]
probably should remove this from the other example actually. like technically it works but it doesn't look right. it's not in the upstream TWBS examples either: http://getbootstrap.com/components/#btn-dropdowns-single

**Comment by sillyslux** [comment]
oh, really? it's useful though.
On the other side, users can override the styling with a custom class and custom css anyway.
So... whatever...

**Comment by taion** [comment]
See other issues – if you're using `data-toggle`, you're doing something quite wrong

**Comment by sillyslux** [comment]
Custom class and custom css has nothing to do with data-toggle.
if you want to discuss #2510, please do it there.

**Comment by jquense** [comment]
for button styles we don't actually want to show the Link versions of Dropdowns b/c they aren't technically supported.

But you can add/use them in your own code without forking or editing check out https://react-bootstrap.github.io/components.html#custom-styles and just add in `link` as a "custom" style

**Comment by sillyslux** [comment]
yea custom class/custom css, my words...  
but then, where do these unsupported link versions come from? will they be removed? that removal will break then, won't it?

**Comment by sillyslux** [comment]
i'm using the link versions right now and thus i have to apply only little custom css.
_am i doing this one wrong too?_

**Pull request closed without merging**
