### PR TITLE
[Added] Implements a left-aligned version of tabs

### PR DESCRIPTION
**Pull request by ctaymor**
As discussed in issue #1111

### CODE REVIEW

**Comment by taion** [comment]
I'm going to take a look at https://github.com/react-bootstrap/react-bootstrap/pull/1109#discussion_r36894258 first, then I will check this.

**Comment by taion** [comment]
LGTM. Need one more reviewer from @react-bootstrap/collaborators.

**Comment by mtscout6** [comment]
screen shot 2015-08-12 at 1 55 53 pm

I'm presuming that line on the bottom is because of the Bootstrap CSS have you looked into any way to not have that there without custom css or style attributes? If if can't be removed it might be worth documenting how to override that with css.

**Comment by taion** [comment]
Oh, good catch! I think we should just get rid of `.nav-tabs` in this case - they're not really tabs, per se, and we just want the `stacked` nav pills styling anyway.

**Comment by taion** [comment]
I'm going to PR to your branch shortly - I think I might need this.

**Comment by taion** [comment]
I PRed https://github.com/pivotal-cf/react-bootstrap/pull/1 onto your branch - has a fix for the issue @mtscout6 pointed out, plus generalizes the implementation a bit.

**Comment by taion** [comment]
I believe the merge conflicts are largely w/#1156.

I'm okay with merging this as soon as the conflicts are resolved. Need one more reviewer from @react-bootstrap/collaborators though.

**Comment by taion** [comment]
I'm going to release v0.24.5 shortly, but I'll hold off on releasing a new alpha until this PR is merged.

**Comment by atomanyih** [comment]
@taion We fixed the conflicts. How does it look?

**Comment by taion** [comment]
It looks like you removed the changes from https://github.com/pivotal-cf/react-bootstrap/pull/1.

**Comment by atomanyih** [comment]
@taion Whoops our bad... would you mind making the pull request again?
We tried cherry-picking but it took your name off the commit :(

**Comment by taion** [comment]
Re-PRed.

**Comment by taion** [comment]
Cool, my changes are in now - can I get one more reviewer?

**Comment by ctaymor** [comment]
Thanks for re-PRing. We merged that in.

**Comment by mtscout6** [comment]
I'm pretty sure our changelog tool is [case sensitive](https://github.com/mtscout6/mt-changelog/blob/master/src/parse-cli-args.js#L4). An issue worth rectifying, though in the mean time can you amend your commit message to change `[Added]` to `[added]`.

**Comment by taion** [comment]
Feel free to just squash in my changes as well. Are we okay with the rest of the code though?

**Comment by AlexKVal** [comment]
LGTM.
(Animation works too)

Added demo looks like:
screen shot 2015-08-19 at 11 35 04 am

--
I like readability added by this PR https://github.com/pivotal-cf/react-bootstrap/pull/1/
Now I'll try to write all new code such clear way. 
This is a good lesson for me. Thank you @taion.

**Comment by taion** [comment]
Okay, we're good to merge as soon as that commit comment gets fixed.

**Comment by AlexKVal** [comment]
Let it be :smiling_imp:

**Comment by taion** [comment]
:clap:

**Comment by AlexKVal** [comment]
:blush:

**Comment by mathieumg** [comment]
:tada: :cherries:

**Pull request merged**
