### PR TITLE
fix: rendering bug of gatsby (maybe)

### PR DESCRIPTION
**Pull request by mxschmitt**
maybe fixes: #3540

could not reproduce it locally on my environment anymore.

### CODE REVIEW

**Comment by mxschmitt** [comment]
The CI pipeline will pass once #3678 is merged.

**Comment by mxschmitt** [comment]
@dependabot recreate

**Comment by taion** [comment]
well, it can't hurt

**Comment by jquense** [comment]
still broken in the deploy link :/ this is such a weird bug

**Pull request closed without merging**
