### PR TITLE
[fixed] Accidental breaking change in Modal trigger

### LINKED ISSUE #929: ModalTrigger: no backward in minor version changes
You removed ModalTrigger, now all projects with this component are broken. And all this in minor version changes.

### PR DESCRIPTION
**Pull request by jquense**
fixes #929

### CODE REVIEW

**Comment by taion** [comment]
LGTM

What do you think about separating out the "autoFocus/enforceFocus/backdrop" logic into a separate visible component from the modal dialog component itself? Might help with the kinds of patterns per #929.

**Comment by taion** [comment]
Should we release v0.23.7 for this?

**Comment by mtscout6** [comment]
Yes we should

**Comment by jquense** [comment]
Normally I'd say we should also add a test that catches this, but since ModalTrigger being removed in the next major bump maybe its not needed.

**Pull request merged**
