### PR TITLE
Add table headers

### PR DESCRIPTION
**Pull request by mwanji**
This PR adds a `headers` prop to `Table`. `headers` is an array of strings that generates the column headers in <thead>, as well as an empty <tbody>. It removes a fair bit of boilerplate.

### CODE REVIEW

**Comment by taion** [comment]
I'm inclined against merging this. We've generally been preferring more explicit and flexible APIs.

**Comment by mwanji** [comment]
Would you prefer something like this?
```
<Table>
  <Headers><Header>Col 1</Header></Headers>
  <Body>
    ...
  </Body>
</Table>
```

Right now, Table doesn't seem to add a lot of value.

**Comment by taion** [comment]
That's a good thing! It's exactly like working with a standard `<table>` - we just wrap up some of the Bootstrap styling bits to be a little cleaner.

**Comment by taion** [comment]
I'm going to go ahead and close this for now. Thanks for the PR, and the code looks good, but I don't think this API is where we want to go.

It's slightly simpler/cleaner only for the case where you have one header per column, and all of your headers are strings. It's not super expressive when the headers might be React nodes, and doesn't let you do things like apply `colspan`.

Given that, the convenience added here is insufficient to justify expanding the API surface area, as I think the current API looks good enough given that it's just standard HTML table markup.

**Comment by mwanji** [comment]
I accept your rejection, but my proposal seems quite similar to how Panel has header and footer props and ListGroupItem has a header prop.

**Pull request closed without merging**
