### PR TITLE
Merge v0.24

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by mtscout6** [comment]
Hooray!!

**Comment by mathieumg** [comment]
All tests passs! :tada:

**Comment by mtscout6** [comment]
> the overlaytriggers with trigger='click' and rootClose={true} don't work
> specifically, in the trigger behaviors example, nothing visible happens when you click on the "Click + rootClose" trigger button
> eyeballing the components page, everything else seems fine

From @taion in the gitter room

**Comment by taion** [comment]
@jquense Do you think you'll have a chance to look at the overlay + rootClose regression?

**Comment by jquense** [comment]
@taion gonna look into right now!

**Comment by dozoisch** [comment]
:tada:

**Comment by jquense** [comment]
@taion figured it out. animation is the worst :/ where do you want me to push this? Merge and I'll PR it?

**Comment by taion** [comment]
I'm on trains for the next 3 hours or so - if you have a fix, I would first merge this, then PR your fix.

**Pull request merged**
