### PR TITLE
OverlayTrigger: Remove extra comma in createChainedFunction call

### PR DESCRIPTION
**Pull request by jiayihu**
Noticed this error while inspecting the code (:

### CODE REVIEW

**Comment by jquense** [comment]
LGTM, why did this compile?

**Comment by taion** [comment]
It's valid ESwhatever

**Comment by dozoisch** [comment]
@jquense http://babeljs.io/docs/plugins/syntax-trailing-function-commas/ for reference. The proposal is stage 4 now!

**Comment by jquense** [comment]
@dozoisch huh I didn't realize it was so far along, nice.

**Comment by taion** [comment]
It's going to be required in the Airbnb style guide as soon as ESLint actually adds a rule for it 😆

**Pull request merged**
