### PR TITLE
Update coverage config

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by dozoisch** [comment]
LGTM!

**Comment by taion** [comment]
Oops, this is incomplete. One sec.

**Comment by taion** [comment]
The coverage drop isn't real. It's just a change in the way it's calculated.

**Comment by taion** [comment]
Switching to Codecov because Codecov actually shows patch-level coverage diffs.

**Comment by dozoisch** [comment]
Awesome

**Pull request merged**
