### PR TITLE
[fixed] Modal div.modal-content should not have hidden class

### PR DESCRIPTION
**Pull request by cymen**
Vanilla Bootstrap Modal does not have the CSS class `hidden` by default on the `div.modal-content`. It was added to react-bootstrap in commit https://github.com/react-bootstrap/react-bootstrap/commit/13f395d2304727d65ee22242423150c22b73addb that added support for bsStyle property to Modal for setting the header color. There were a number of changes and why `hidden` was added to `div.modal-content` isn't clear.

My reason for not wanting this is when using say react-select inside a modal, the dropdown should be visible in the event it overflows the modal.

### CODE REVIEW

**Comment by dozoisch** [comment]
don't worry about failing tests, I will rerun the tests once #604 is merged

**Comment by AlexKVal** [comment]
I've re-run TravisCI tests. They are green now.

**Comment by AlexKVal** [comment]
to @cymen
> ... why `hidden` was added to `div.modal-content` isn't clear.

The reason is https://github.com/react-bootstrap/react-bootstrap/pull/403#issuecomment-75965860

And then "Reason for (overflow:hidden) change on Modal #448" issue with the bug has been created.

Author has acknowledged the bug https://github.com/react-bootstrap/react-bootstrap/issues/448#issuecomment-78350077 and he just have no time to fix it https://github.com/react-bootstrap/react-bootstrap/issues/448#issuecomment-86364657.

Therefore it seems you need to make sure that your solution doesn't introduce regression for https://github.com/react-bootstrap/react-bootstrap/pull/403#issuecomment-75964220

And if you address all of it, chances are, you also solve #448 :sparkles:

**Comment by mtscout6** [comment]
@stefanfisk This looks like the beginning of your bug fix. Do you have any input on this?

**Comment by cymen** [comment]
@AlexKVal Thanks for digging those links up -- I didn't think to check in the right place and now it makes sense.

**Comment by AlexKVal** [comment]
@cymen You are welcome :sparkles:

**Comment by cymen** [comment]
This PR does cause a regression on as illustrated in #403. I'll keep working on it -- I think bootstrap modal does indeed to the workaround of only applying `overflow: hidden` if a bsStyle is applied. I'm confirming that and will update this PR.

**Comment by cymen** [comment]
The fix for the regression is to apply to `.modal-header` if `bsStyle` is a property of Modal this CSS:

```css
    border-top-left-radius: inherit; 
    border-top-right-radius: inherit;
```

This is IE 9+.

After researching this more, I would advocate for react-bootstrap not supporting bsStyle on the modals (vanilla bootstrap does not and I think that is likely for good reasons). It causes a headache that is best pushed down to those consuming react-bootstrap. But maybe the above solution is acceptable.

**Comment by mtscout6** [comment]
@cymen I created twbs/bootstrap#16431 let's see where that goes.

**Comment by AlexKVal** [comment]
> I would advocate for react-bootstrap not supporting bsStyle on the modals (vanilla bootstrap does not and I think that is likely for good reasons). It causes a headache that is best pushed down to those consuming react-bootstrap.

:+1:

**Comment by mtscout6** [comment]
I would agree with that, @stefanfisk I'm sorry but we will need to take this out.

**Comment by stefanfisk** [comment]
No worries, it was a quick and dirty idea that turned out to be terrible.

**Comment by mtscout6** [comment]
@cymen can you change the docs to not be demonstrating use of bsStyle, and remove these two lines: https://github.com/react-bootstrap/react-bootstrap/blob/v0.21.2/src/Modal.js#L102-L103. Then this should be ready to merge in.

**Comment by cymen** [comment]
@mtscout6 Sure -- there were a few more changes but I think I got everything in 379ea3ecbcf0cb2838a6cf85fc8fd9a3d07240ea

**Comment by AlexKVal** [comment]
LGTM :+1:

**Pull request merged**
