### PR TITLE
Pass wrapperStyle and wrapperClassName to react-overlay/Modal

### PR DESCRIPTION
**Pull request by jesenko**
Related to #1526.

### CODE REVIEW

**Comment by taion** [comment]
This is failing on Lint.

I'm inclined against merging this - seems like at this point you're better off just using react-overlays directly. @jquense?

**Comment by jesenko** [comment]
Fixed Lint error. I considered just using react-overlay directly, however I actually use all styling / functionality from bootstrap _except_ for setting `z-index` - bootstrap version does not handle stacked modals. Setting `z-index` on wrapper solves the issue.

Considering that `backdropClassName`/`backdropStyle` and `containerClassName`/`containerStyle` are already passed to underlying react-overlay Modal, would it not be more consistent to do the same for the wrapper?

**Comment by jquense** [comment]
yeah...I'd like to hear the use case where you need 99% of the bootstrap model but also this hook. My thought is is the same, that if you need to style or add classes to the outer wrapping element that you might want to just use the raw Modal.

If you are looking for stackable modals: i'd use: https://github.com/jquense/react-bootstrap-modal

its a more complete solution to that.

**Comment by jesenko** [comment]
@jquense Great, thanks for the link, I will try switching to `react-bootstrap-modal`, seems like an ideal match. I will close this PR/and related issue...

**Pull request closed without merging**
