### PR TITLE
Split commit of PR #939

### PR DESCRIPTION
**Pull request by firework1230**
This PR is the same as #939 to fix two bugs in Pagination, but split the commit for corresponding bugs.

### CODE REVIEW

**Comment by mtscout6** [comment]
It looks to me like there is a disconnect on where we start counting. Normally with Arrays we start at 0, but when dealing with human readable page numbers we start with page 1 not page 0. I'm guessing at the moment that this is more of a documentation issue.

**Comment by AlexKVal** [comment]
After this patch:

With `items={0}`
screen shot 2015-07-06 at 9 57 50 pm


With `items={1}`
screen shot 2015-07-06 at 9 57 55 pm

One page => `1` button with number `1` 

LTGM :+1: 

As I've already mentioned https://github.com/react-bootstrap/react-bootstrap/pull/939#issuecomment-118533484
Tests are already written by me, I will PR them after this will be merged
(otherwise they will fail on travisCI)

What did you mean about `a disconnect on where we start counting` `@mtscout6 ?

**Comment by mtscout6** [comment]
I thought for some reason he was trying to say the active page is page 0. Looking at it again, I think I misunderstood.

**Comment by AlexKVal** [comment]
Then what do you think ? I merge it ?

These bug-fixes works OK on the DOCs page 
and are OK with my tests which only I have seen so far :smile:

**Comment by AlexKVal** [comment]
Tests which I'm talking about #950

**Comment by mtscout6** [comment]
LGTM

**Comment by AlexKVal** [comment]
@firework1230 Thank you for noticing and fixing those bugs :sparkle: :sparkle: 
:cherries:

**Comment by roadmanfong** [comment]
I didn't notice that. Thanks for fixing. :smiley:

**Pull request merged**
