### PR TITLE
Add support for Spinners

### PR DESCRIPTION
**Pull request by tjdavey**
Adds support for the [spinners components](https://getbootstrap.com/docs/4.2/components/spinners/) introduced in Bootstrap 4.2.

*Changes:*
- Adds new `Spinner` component
- Add tests for new component
- Creates new page in documentation for new component
- Upgrades documentation CSS to Bootstrap 4.2 (given the claimed 4.2 support in the documentation itself) 

*Notes:*
- I wasn't sure about the terminology for the property that switches between the two styles of spinner component. I couldn't think of a good term that wouldn't overlap with an existing property. `animation` was chosen at it was the most representative of the changes the property made, but I feel it may still be too ambiguous. I'm open to alternative suggestions.
- Whilst the documentation claims compatibility with Bootstrap 4.2 it was using a Bootstrap 4.1 CSS file. I've upgraded the documentation to a Bootstrap 4.2 version of the CSS file. I can remove this change and submit seperately if necessary.

### CODE REVIEW

**Comment by tjdavey** [comment]
> cool! can we add a type signature as well, for the TS users?

I'll add it now.

**Comment by taion** [comment]
Thanks!

**Comment by jquense** [comment]
this is awesome

**Comment by tjdavey** [comment]
@taion I've added the Typescript support. I don't have the deepest understanding of the way the Typescript definitions are structured for this project so it might be worth just checking the details of my implementation.

**Comment by davecarlson** [comment]
Any news when beta 6 will be released so we can use these without pulling in master ? 

:)

**Comment by jquense** [comment]
soon!

**Pull request merged**
