### PR TITLE
Load custom eslint rules, including a spread aware shorthand rule

### PR DESCRIPTION
**Pull request by jquense**
Fixes that dang false eslint warning about using spread properties in an object.

Prior art on this: https://github.com/facebook/react/pull/4034

### CODE REVIEW

**Comment by mtscout6** [comment]
This seems like a very generic problem that is not isolated to react-bootstrap, and it also seems tricky to maintain over time. Perhaps pushing this to a new npm module that adds this rule would be good? That would have the added benefit of being usable in react-router-bootstrap if we end up needing it there. The goal of course being to deprecate that module once eslint truly supports es7.

**Comment by jquense** [comment]
the particular rule is generic and would work great in its own npm repo, and that makes the most sense probably. I don't particularly want to own said repo independently, but if we wanted to add it to the org that seems like a good idea, and I'd be happy to maintain it. Not having rights to make new repos this was the next easiest thing :).

Aside from that particular rule we might want to have custom eslint rules that are bootstrap specific, which was another reason i went this approach. That being said I have no idea what those rules might be, and we can always just cross that bridge then if the need ever arises and feels worth it.

**Comment by jquense** [comment]
We will solve this particular thing in either babel-eslint or a seperate repo in the babel org

**Comment by taion** [comment]
It'd be great if this could go in `babel-eslint` or similar - would like to minimize the number of packages I need in my scaffolding.

**Comment by jquense** [comment]
so as a of a few minutes ago [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel) is now a thing. but hopefully if this goes through, https://github.com/eslint/eslint/pull/2793 we can just move it into babel-eslint itself

**Comment by mtscout6** [comment]
@jquense do you still need this branch?

**Comment by jquense** [comment]
nope! thanks for the reminder :)

**Pull request closed without merging**
