### PR TITLE
Update Checkbox.js to apply title to label

### PR DESCRIPTION
**Pull request by Billy-**
RE: #2634

### CODE REVIEW

**Comment by jquense** [comment]
looks ok to me, can you fix the lint issue tho please thanks

**Comment by Billy-** [comment]
Sorry, I edited on GitHub so didn't see that. Have just pushed another commit which should fix it.

**Comment by taion** [comment]
This should apply to `<Radio>` as well, at least.

Probably also all the other cases where we pass `className` and `style` to the parent, but other props to the child?

**Comment by Billy-** [comment]
Probably, I'm afraid I don't have time to do all of them, at least not any time soon. We're very pushed for time on our current project :confounded:. Sorry!

**Comment by Billy-** [comment]
Any chance this can be merged and a separate issue filed for the other inputs? If no one has time to do it there's no point holding this back...

**Comment by hostr** [comment]
> We'd like to fix Radio at least, they are essentially the same input so the fix should be quick

Done -> https://github.com/react-bootstrap/react-bootstrap/pull/2647

**Pull request merged**
