### PR TITLE
Use webpack-dev-server instead of webpack-dev-middleware

### LINKED ISSUE #623: Change local docs run to use webpack-dev-server instead of webpack-dev-middleware
The command `npm run docs` is supposed to watch for file changes and reload/recompile everything necessary. For any of the modules that are loaded server side this is not the case, which is problematic with the isomorphic approach we have been trying. What we need to do is use the webpack-dev-server and proxy to a server back-end that gets reloaded with either supervisor or nodemon.

### PR DESCRIPTION
**Pull request by mtscout6**
Will update changes files both server and client side without needing to
restart.

Resolves #623

### CODE REVIEW

**Comment by dozoisch** [comment]
yay! no more reloading

**Comment by aabenoja** [comment]
Well this didn't take very long...

**Comment by AlexKVal** [comment]
Awesome! This is much better! :+1: 
See what `The Skill` can do! :smile: 


I would add a couple strokes:
- remove `;` from [here](https://github.com/react-bootstrap/react-bootstrap/pull/628/files#diff-ce9d98be04f7a23d325c274fc1a0a089R21)
- then remove next line `app = app` [here](https://github.com/react-bootstrap/react-bootstrap/pull/628/files#diff-ce9d98be04f7a23d325c274fc1a0a089R23)
- then next `.use()` block shift left to aline with apper `app.get()` block.

- rewrite [this line](https://github.com/react-bootstrap/react-bootstrap/pull/628/files#diff-ce9d98be04f7a23d325c274fc1a0a089R41) into just `app.use(express...)`

You can safely remove the `.use(webpackCrossOrigin)` block from [here](https://github.com/react-bootstrap/react-bootstrap/pull/628/files#diff-ce9d98be04f7a23d325c274fc1a0a089R24)
Now it's all working without it.

Simplify [here](https://github.com/react-bootstrap/react-bootstrap/pull/628/files#diff-ce9d98be04f7a23d325c274fc1a0a089R45) like this:
```js
app.listen(port, function () {
  console.log(`Server started at http://localhost:${port}`);
});
```

And just another cosmetic stroke I would say:
`app.all()` => `app.get()` [here](https://github.com/react-bootstrap/react-bootstrap/pull/628/files#diff-ce9d98be04f7a23d325c274fc1a0a089R19)
There is no other http verbs now.

P.S. I've learned a lot from this PR. Thank you!

**Comment by AlexKVal** [comment]
I could merge this PR, because it has already `3x :+1:`
and then create PR with those proposed changes.

But I'm not sure this is the right way and because of that
I've just written my proposals in comment.

**Comment by mtscout6** [comment]
I can do that little cleanup the second I get into the office. Give me
about an hour from now.

**Comment by mtscout6** [comment]
Nevermind I did it on the train! The only suggestion I didn't take was the removal of the semi-colon as that produces an eslint error.

**Comment by AlexKVal** [comment]
> Nevermind I did it on the train!

That's a spirit ! :smile:  :+1: 

With this merged it seems it's time to make new release :wink:  What do you think ?

**Comment by AlexKVal** [comment]
> The only suggestion I didn't take was the removal of the semi-colon

I can live with it ! :blush:

**Pull request merged**
