### PR TITLE
Added badge support for tabs

### PR DESCRIPTION
**Pull request by ilyadoroshin**
Needed this feature for one of my projects.

### CODE REVIEW

**Comment by mtscout6** [comment]
Why not just do something like this:

```
var withBadge = <span>Tab 1 <Badge>2</Badge></span>;

var tabbedAreaInstance = (
    <TabbedArea defaultActiveKey={2}>
      <TabPane eventKey={1} tab={withBadge}>TabPane 1 content</TabPane>
      <TabPane eventKey={2} tab="Tab 2">TabPane 2 content</TabPane>
    </TabbedArea>
  );

React.render(tabbedAreaInstance, mountNode);
```

You can give that a try on the [docs components page](http://react-bootstrap.github.io/components.html#tabs). It rendered the badge just fine for me.

**Comment by ilyadoroshin** [comment]
@mtscout6 oh, looks awesome, man :) never knew that it's ok to put components there)
Thanks!

**Comment by mtscout6** [comment]
@ilyadoroshin Do you still feel that this PR is needed or does that solution work for you. If not needed please close.

**Comment by ilyadoroshin** [comment]
@mtscout6 ok, will close this one. And thanks for your explanations! 
I think it'd be great if you could add this into docs. Cuz it's not that straightforward sometimes. 
Thanks!

**Pull request closed without merging**
