### PR TITLE
docs: upgraded mdx

### PR DESCRIPTION
**Pull request by mxschmitt**
fix: #3679

Upgrading the major version bump of mdx.

Reference: https://mdxjs.com/migrating/v1/
`gatsby-mdx` bump Reference: https://github.com/ChristopherBiscardi/gatsby-mdx/releases/tag/v0.6.1

### CODE REVIEW

**Comment by taion** [comment]
Looks like this is the error from the build: https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=object&args[]=

**Comment by mxschmitt** [comment]
I mean this error, which occurs when are starting the Gatsby development server. idk.
image

**Comment by mxschmitt** [comment]
By more digging into this issue, I found out, that this HOC will never be executed:
https://github.com/react-bootstrap/react-bootstrap/blob/c0f98846b0a28173379fec3242a084e32d9939d2/www/src/withLayout.js#L7-L24

**Comment by jquense** [comment]
do we know why at this point?

**Comment by bpas247** [comment]
> By more digging into this issue, I found out, that this HOC will never be executed:
> [react-bootstrap/www/src/withLayout.js](https://github.com/react-bootstrap/react-bootstrap/blob/c0f98846b0a28173379fec3242a084e32d9939d2/www/src/withLayout.js#L7-L24)
> 
> Lines 7 to 24 in [c0f9884](/react-bootstrap/react-bootstrap/commit/c0f98846b0a28173379fec3242a084e32d9939d2)
> 
>  return props => { 
>    const { pathname } = props.location; 
>    let Layout = DefaultLayout; 
>    if ( 
>      pathname.startsWith('/getting-started') || 
>      pathname.startsWith('/layout') || 
>      pathname.startsWith('/components') || 
>      pathname.startsWith('/utilities') 
>    ) { 
>      Layout = ApiLayout; 
>    } 
>   
>    return ( 
>      <Layout location={props.location}> 
>        <Component {...props} /> 
>      </Layout> 
>    ); 
>  };

Where is `withLayout` being used?

**Comment by mxschmitt** [comment]
Hi guys, now everything should be fixed, please check :)

@jquense is this (`gatsby-transformer-react-docgen`) still necessary/are your PRs merged?

https://github.com/react-bootstrap/react-bootstrap/blob/ec732b96b9453ba7a5b767edfa0eb81a89975040/www/package.json#L25-L30
So that we can switch back to the normal version of: `gatsby-transformer-react-docgen`.

**Comment by jquense** [comment]
> is this (gatsby-transformer-react-docgen) still necessary/are your PRs merged?

It shouldn't be anymore we can upgrade to v4

**Comment by mxschmitt** [comment]
@jquense please take a look and approve if you are okay with it :)

**Pull request merged**
