### PR TITLE
Force hide tooltip when clicking on OverlayTrigger

### PR DESCRIPTION
**Pull request by keul**
This prevent tooltip to remain open if hover area became disabled.

See discussion at #2969

### CODE REVIEW

**Comment by taion** [comment]
I don't think this quite makes sense to unconditionally hide the tooltip on any click.

**Comment by keul** [comment]
@taion do you have any alternative suggestion? If my analysis at #2969 is right is not simple to solve this as we are hitting a browser behavior.

**Comment by mxschmitt** [comment]
closed due inactivity.

**Comment by jakeNiemiec** [comment]
@mxschmitt #2969 Can also be closed then.

**Pull request closed without merging**
