### PR TITLE
[fixed] isRequiredForA11y check should be against undefined

### PR DESCRIPTION
**Pull request by kennyw12**
We were getting silent a11y fails and found this bug.

### CODE REVIEW

**Comment by taion** [comment]
Can we just do `== null` to be consistent with how `isRequired` works in React, which considers a prop missing if it's either `null` or `undefined`. That should also un-break the test for free.

**Comment by ctaymor** [comment]
Closing because the problem was fixed in PR [#13](https://github.com/react-bootstrap/react-prop-types/pull/13).

**Comment by AlexKVal** [comment]
@ctaymor you are too fast :smile: 
I recovered it as https://github.com/react-bootstrap/react-bootstrap/pull/1224,
though as it turns, it needs more thoughts.

--
https://github.com/react-bootstrap/react-prop-types/pull/13 is against another project 
which `R-B` doesn' use yet.
https://github.com/react-bootstrap/react-bootstrap/pull/1223 is on the way

--

**Comment by ctaymor** [comment]
@AlexKVal Oops, sorry about that. I was wondering why just typing "#13" didn't get the right story. :)

**Pull request closed without merging**
