### PR TITLE
[removed] non-standard onClick props for ListGroup and ListGroupItem

### PR DESCRIPTION
**Pull request by stefanfisk**
Old behaviour can be implemented using custom onClick handlers.

### CODE REVIEW

**Comment by stefanfisk** [comment]
Fixes #373.

**Comment by mtscout6** [comment]
Did you intend to put those other two commits here?

**Comment by stefanfisk** [comment]
No, I just fucked up and didn't notice I was on the wrong branch when doing the modal bsStyle stuff. They'll disappear in the squash once this PR is done.

**Comment by mtscout6** [comment]
Guess I should have said Resolves #408 in that merge commit message, oops. Either way that one commit is not in master.

**Pull request closed without merging**
