### PR TITLE
v5: Add fullscreen modal support

### PR DESCRIPTION
**Pull request by kyletsang**
Adds prop `fullScreen` which supports `true` or breakpoints `sm` and up.

https://v5.getbootstrap.com/docs/5.0/components/modal/#fullscreen-modal

### CODE REVIEW

**Comment by kyletsang** [comment]
Yeah majority is usually "up".  One exception from v4 that comes to mind is the fluid containers.  Those ones are 100% width up until the specified breakpoint.

**Comment by BestUkpai** [comment]
wow so amazing

**Comment by jquense** [comment]
The fluid containers map to the classes tho right? It's `container-sm` not `container-sm-down`, that these classes include the `down` makes wonder if we should be more explicit as well, if only in case they add a `*-up` variants? I don't have a lot of suggestions tho on prop naming :/ `maybe fullscreen='sm-down'` is ok?

**Comment by kyletsang** [comment]
`fullscreen="sm-down"` works and is more clear.  I wonder if bootstrap will rename their container classes in the future to align the naming with behavior.  

I'll fix up this PR.

**Pull request merged**
