### PR TITLE
Update components to use external prop-types instead of React

### LINKED ISSUE #2547: Replace React.PropTypes usage
React 15.5 (RC) shows warnings
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

### PR DESCRIPTION
**Pull request by sorahn**
Fixes #2547 

I upgraded all the components with the official [`react-codemod`](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types).  After that I went through and cleaned up all the files that it couldn't automatically do. 

When I tried to run the tests I got a bunch of errors that looked like this
```
    Error: Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.
        at Object.<anonymous> (webpack:///test/index.js:22:0 <- test/index.js:78:12)
        at Function.invoke (node_modules/sinon/pkg/sinon.js:2651:59)
        at Object.proxy [as error] (eval at createProxy (node_modules/sinon/pkg/sinon.js:2556:17), <anonymous>:1:35)
        at printWarning (webpack:///~/fbjs/lib/warning.js:36:0 <- test/index.js:3605:18)
        at warning (webpack:///~/fbjs/lib/warning.js:60:0 <- test/index.js:3629:23)
        at Object.createRendererWithWarning [as createRenderer] (webpack:///~/react-dom/lib/ReactTestUtils.js:42:0 <- test/index.js:88693:12)
        at QueryCollection.shallowRender (webpack:///~/teaspoon/element.js:124:0 <- test/index.js:90718:55)
        at Context.<anonymous> (webpack:///test/FormGroupSpec.js:71:0 <- test/index.js:99015:11)
```
I'm not sure what's up with that but it happens in the master branch too.

### CODE REVIEW

**Comment by jquense** [comment]
thanks for doing this, gonna take a bit to review, but much appreciated

**Comment by taion** [comment]
seems okay as long as the travis tests pass? i'd prefer the imports were alphabetized but i guess the codemod doesn't do that

**Comment by jquense** [comment]
_no one_ does that :P ;) Ya looks good to me

**Comment by sorahn** [comment]
@taion how would you want imports sorted in this case:
```
import code from 'code'
import { bar } from 'foo'
```

And would you want a blank line between global imports and local imports?

**Comment by jquense** [comment]
If you want to sort them. Sort them by path, grouped by global and local, with a line between the global and local groups.

It's really not required tho if you don't have time for that

**Comment by sorahn** [comment]
> Sort them by path, grouped by global and local.

Ohhh, by path.  Interesting.

Sorting modules is something that I actually do in my personal projects, but I just have sublime run 'sort' on a set of lines.  It gets slightly more tricky with a large destructured import, but I try.

I'm still interested in automating this process (babel plugin maybe?), and your desired order actually resolves my issue with what to do with large destructured ones.

Woud you also want the imports sorted if a single line?
```
import { code, bar, derp } from 'libs' 
//=>  import { bar, code, derp } from 'libs' 
```
Just curious now, won't come in this pull request, there are some schemes now :)

**Comment by taion** [comment]
Sorry I mean don't take the time to go alphabetize the imports in this massive package

**Comment by andy-j-d** [comment]
I'm working on a PR to @sorahn that will fix the shallow renderer errors.

**Comment by bguggie** [comment]
any update on this?

**Comment by sorahn** [comment]
@taion just stumbled across this. https://github.com/bfncs/codemod-imports-sort

**Comment by jquense** [comment]
Good to know about that!

**Comment by jquense** [comment]
I'll release something next week unless @taion gets a chance. Thanks!

**Comment by taion** [comment]
released in v0.30.9

**Comment by jorrit** [comment]
Maybe semver minor would have been more appropriate for this change?

**Pull request merged**
