### PR TITLE
Add active class if props.active is set

### PR DESCRIPTION
**Pull request by chilts**

### CODE REVIEW

**Comment by thetimbanks** [comment]
:+1: This looks good to me. It looks like some code got lost from [this PR](https://github.com/react-bootstrap/react-bootstrap/pull/686) during the es6 class refactor and this fills in the gaps.

**Comment by chilts** [comment]
Thanks for merging! :)

**Comment by chilts** [comment]
Oh wait, sorry, you haven't merged yet (I was looking at that other one). Well, thanks for the review. :)

**Comment by taion** [comment]
LGTM. Need one more reviewer from @react-bootstrap/collaborators.

**Comment by apkiernan** [comment]
LGTM

**Comment by mathieumg** [comment]
LGTM. Wouldn't you want a test that ensures the class is added when that prop is present?

**Comment by chilts** [comment]
@mathieumg Yes! I totally should have done that. I'll go and dig in deeper and find the right place to add it. I'll look at it tomorrow (almost bed time for me now).

**Comment by mtscout6** [comment]
Can you also amend your commit message to follow our [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md#commit-subjects-for-public-api-changes)? Our automated changelog tool uses this format to document the change on the next release.

**Comment by taion** [comment]
I merged this by hand: https://github.com/react-bootstrap/react-bootstrap/commit/a1bd9346a14c54c1ddd4b5ae5c3f9a4405f5c92e

**Comment by chilts** [comment]
Thanks @talon. Sorry, I couldn't get to this on Friday or the weekend.

**Pull request closed without merging**
