### PR TITLE
Add request for screenshots/screencasts for visual changes

### PR DESCRIPTION
**Pull request by mtscout6**
Proposed in https://github.com/react-bootstrap/react-bootstrap/pull/887#issuecomment-115276160

/cc @mathieumg

### CODE REVIEW

**Comment by mathieumg** [comment]
Awesome! :tada: Thanks. :+1+

**Comment by mtscout6** [comment]
It was less effort to write up, then to create an issue to eventually write it up :wink:

**Comment by jquense** [comment]
LTGM

**Comment by AlexKVal** [comment]
nice :sparkle:

**Pull request merged**
