### PR TITLE
Add prop that prevents dropdown from closing on click

### PR DESCRIPTION
**Pull request by codebreach**
this is used for multiple select dropdowns
the prop added is `preventCloseOnItemSelect `

Please let me know if you have a better name for it

### CODE REVIEW

**Comment by codebreach** [comment]
Turns out this doesnt work because of `RootCloseWrapper`
Any ideas on how to make this work?

**Comment by jquense** [comment]
thanks for the PR. I think this approach isn't quite ideal, generally we'd like behavior like this to be controlled via the dropdown `onToggle`/`open` props which let the user more flexibily control when the dropdown closes in response to it's events. The one missing bit there however, is the information about what triggers an onToggle. 

You can check out https://github.com/react-bootstrap/react-bootstrap/issues/1490 for some conversation about this.

**Comment by codebreach** [comment]
Right. I was trying to use the same approach but realized that there is no way to tell if the onToggle is called by the component internally or externally.

Looking at #1490 it seems that the best way to do this would be to pass a source argument to onToggle and let the consumers use that. 

I can try doing that in this PR if you are willing to merge that?

**Comment by codebreach** [comment]
Also, what do you expect source argument look like?
Like how do we tell its coming from the component and not form an external event?

**Comment by jquense** [comment]
so generally i'd pass an object as a second argument to the onToggle callback something like:

```js
onToggle(open, { source: 'select' })
```

where source can be: ''select'`, '`keyboard'`, `'clickoutside'` or similar...we can bikeshed the names

**Comment by taion** [comment]
Closing this PR given that we're not going to use this approach.

**Comment by codebreach** [comment]
Is this functionality getting merged in another PR?

**Comment by taion** [comment]
In a different form as https://github.com/react-bootstrap/react-bootstrap/pull/2422

**Pull request closed without merging**
