### PR TITLE
Stop passing non-dom attributes in Badge

### PR DESCRIPTION
**Pull request by liorbentov**
See https://github.com/react-bootstrap/react-bootstrap/issues/1994

### CODE REVIEW

**Comment by jquense** [comment]
Thanks for the PR and helping us fix this issue! I'm surprised that this passes lint since this leaves a bunch of unused variables...@taion?

This is certainly a pattern i've used before myself but I think in this project we want to be a bit clearer about what is going on so that others don't accidentally remove these lines thinking they aren't needed.

An approach we use elsewhere: https://github.com/react-bootstrap/react-bootstrap/blob/v0.29.5/src/FormControl.js#L49 is to `delete` the props off of the remaining props.

Alternatively we can use `lodash/omit`

**Comment by jquense** [comment]
@liorbentov see https://github.com/react-bootstrap/react-bootstrap/pull/2003 for the conversation about how to structure these PR's

**Comment by liorbentov** [comment]
@jquense, how about now?

**Comment by taion** [comment]
Replaced by https://github.com/react-bootstrap/react-bootstrap/pull/2026

**Pull request closed without merging**
