### PR TITLE
Simplifies code contributions and automates the dev setup

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! there, :slightly_smiling_face:
this PR adds support for Gitpod, a free online tool that lets you automate your dev environment, eases the hurdles for contributions and generally working on GitHub projects. It allows anyone to get a ready-to-code dev environment for any branch, issue and pull request with a single click.

You can give it a try on my fork of the repo: https://gitpod.io/#https://github.com/nisarhassan12/react-bootstrap

image

It seems to work well! Please let me know if there is anything that can be improved. I would love to help :)

### CODE REVIEW

**Comment by jquense** [comment]
Hi there thanks for the PR and for trying to decrease the barrier to entry! I'm not super comfortable recommending a tool that I don't use, or interested in getting any additional support complexity from a dev env we don't know or quite understand. Especially given that setup here is already probably less work than signing up for and configuring gitpod. 

I'll let the others weigh in tho!

**Comment by bpas247** [comment]
@nisarhassan12 The tool looks like it could definitely simplify the dev setup that we have, which is something I struggled with when first contributing to this repo actually.

Couple quick questions regarding the usage:
- Will this be able to run our main testing suite (Karma and NodeJS)? Will it also be able to run our TS testing suite?
- In your experience with this tool, how much configuration will we need to maintain for this? I could see the current configuration going stale, if we ever make any major changes to the dev environment.
- Is there a CI/CD tool that could notify us if the dev environment configuration isn't working for a specific branch? Such as if it breaks on master, dev, etc.

Looks pretty interesting so far 😃

**Comment by nisarhassan12** [comment]
@bpas247  Thanks for the feedback! :smile: 

It should be able to run the main testing suite without issues. Currently, it's complaining about a missing Chrome binary, but I'll try to fix that shortly.

However, once the setup is working, I think it's relatively low-effort to maintain. Sure, maybe the dev environment will change in the future, but that's already something every contributor has to deal with today. With Gitpod, you'll only need to fix the script once, instead of having to tell every contributor out there how to fix it themselves and dealing with various different OSes and tool versions etc.

Yes, you can install the [Gitpod hook](https://github.com/marketplace/gitpod-io), which will act like a CI and build your project on every push to any branch or Pull Request. You can configure it [like so](https://www.gitpod.io/docs/46_prebuilds/), or I can do it for you in this PR.

**Comment by nisarhassan12** [comment]
@bpas247 Thanks! the test suite now works. I have made a new PR because somehow due to some Github error the PR was not updating when I update my master branch. So I'm now I made a new one here  #4702 and everything seems to work well.
I'm closing this one.

**Pull request closed without merging**
