### PR TITLE
[fixed] Prevent click on PageItem if disabled

### LINKED ISSUE #412: Disabled PageItem is still a functioning link
Click on the disabled "next" link in the last section of http://react-bootstrap.github.io/components.html#pager and it will jump to the top of the page. It looks like the test for onSelect doesn't actually test if the link is unusable.

Maybe the buttons should not be disabled but instead kill the click event.

### PR DESCRIPTION
**Pull request by krzysiek1507**
Fixes #412

### CODE REVIEW

**Comment by taion** [comment]
AppVeyor failure looks spurious? LGTM. Need one more reviewer.

**Comment by darrenburns** [comment]
Looks fine.

**Comment by taion** [comment]
Still need another reviewer from @react-bootstrap/collaborators.

**Comment by dozoisch** [comment]
LGTM

**Comment by AlexKVal** [comment]
> /cc @AlexKVal

@krzysiek1507 I am sorry. I was too busy these days. :cherries: 
Anyway we have other collaborators to check PRs :smiley:  :sparkle:

**Pull request merged**
