### PR TITLE
Adding Maintainers Documentation

### PR DESCRIPTION
**Pull request by mtscout6**
I have been giving some thought this week to seeking out additional collaborators on this repo. Primarily so I'm not the only bottleneck to getting things done since this project continues to gain support. There are plenty of good folks out there that have already contributed so much and I'm incredibly thankful to all of you. Before I let this out into the wild though I'd like some feedback on this initial draft as to what y'all would like.

/cc @mathieumg @AlexKVal @joemcbride @stevoland @pieterv @trentgrover-wf @JordanTheriault @apkiernan
I'm sure there are others that would be interested in this that I may have missed.

### CODE REVIEW

**Comment by dozoisch** [comment]
:+1: for @mathieumg

**Comment by pieterv** [comment]
@mtscout6 Probably also time you removed @stevoland and myself from the Authors in the main readme and put your own name there :P It has been great to see this project flourish in our absence :)

**Comment by mtscout6** [comment]
@pieterv I didn't want to detract from your initial contribution which was astounding. If anybody is really interested in figuring out who's who they can look at the commit history, or at the organization members. I'd rather just remove that section.

**Comment by pieterv** [comment]
@mtscout6 Removing the section sounds like a good idea, this project is more than just a few people now :)

**Comment by mtscout6** [comment]
Thanks for the feedback everyone!

**Pull request merged**
