### PR TITLE
Remove unused utils

### PR DESCRIPTION
**Pull request by taion**
We should also get rid of TransitionEvents at some point.

### CODE REVIEW

**Comment by jquense** [comment]
is Dom utils really not used?

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/search?utf8=%E2%9C%93&q=domUtils

No hits in code... tests still pass without it.

**Comment by jquense** [comment]
that happened so subtly, nice!

**Comment by taion** [comment]
Is this good to go then?

**Comment by jquense** [comment]
:shipit:

**Pull request merged**
