### PR TITLE
[fixed] ListGroup work with single child contained in array

### LINKED ISSUE #548: ListGroup fails if list contains a single entry
It looks like this bug was introduced by f52380584f842b9db5efae4a96d77369234d5828. I suspect that

    let child = this.props.children;

should be 

    let child = this.props.children[0];

### PR DESCRIPTION
**Pull request by cdock1029**
Check if child is array before accessing props

fixes #548

### CODE REVIEW

**Comment by mtscout6** [comment]
This looks great! Can you squash the commits and prefix your commit message with [fixed] as per the [contributing guidelines (Commit Subjects for Public API Changes section)](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md#commit-subjects-for-public-api-changes) at the root of the repo?

**Comment by mtscout6** [comment]
:+1: 

Needs one more approval from another contributor @react-bootstrap/collaborators

**Comment by dozoisch** [comment]
LGTM

**Comment by mtscout6** [comment]
@cdock1029 Did you see @leth's additonal issues in #548? Does that seem reasonable to also tackle with this PR?

**Comment by cdock1029** [comment]
Yes I can work on that 



—

**Comment by mtscout6** [comment]
Thanks!

**Comment by AlexKVal** [comment]
Comfirm. :+1: 

Before this patch console in browser:
```
Uncaught TypeError: Cannot read property 'href' of undefined
```
error links to the line of code
```js
childrenAnchors = child.props.href ? true : false
```
https://github.com/react-bootstrap/react-bootstrap/blob/v0.21.0/src/ListGroup.js#L19

After this patch both test cases are working OK.

**Comment by mikechau** [comment]
Also running into this issue, patch resolves the problem for me. :+1:

**Comment by mtscout6** [comment]
Thanks for the fix!

**Pull request merged**
