### PR TITLE
Modal tweak

### PR DESCRIPTION
**Pull request by jquense**
Not sure that `Modal.Markup` is the best name...taking suggestions

### CODE REVIEW

**Comment by taion** [comment]
Maybe `ModalDialog`? We should add back the "static modal dialog" example to the components page, though.

**Comment by jquense** [comment]
good call, let me add that back

**Comment by jquense** [comment]
@taion does it make more sense to split the backdrop and onmount container logic out into the Modal component and have the Dialog just be the actual dialog markup? I am not sure its useful to anyone but it makes more sense to me conceptually. then the Dialog component can be dumb

**Comment by taion** [comment]
I think that's the way to do it. Make `ModalDialog` be just a static dialog component. This will also have the added benefit of preventing that example from causing random scrolling bugs every couple of weeks.

**Comment by jquense** [comment]
whelp that ended up being a good bit more work then I thought :P still I think this is better. It also mirrors the upstream twbs modal a bit more structurally which is helpful I think.

**Comment by taion** [comment]
Oof, yeah.

Do you think it makes sense to add a prop to `Modal` such that the user can supply his own `ModalDialog` or equivalent (i.e. make it `cloneElement` a single supplied child rather than use the current render logic)? I think that would address some of the issues @mfunkie brought up on Reactiflux.

I think it'd also otherwise make this `Modal` a lot more useful to people who want to more deeply customize how the dialog itself appears, rather than just using the TWBS modal dialog.

**Comment by jquense** [comment]
ya I think that's a great idea, I wanted to do something similar to address #748 when the original PR went through but couldn't think of a not-ugly way to handle it. A prop is the simplest, maybe we could also do some sniffing with children but I am not sure how that be unambiguous (and not breaking). I also don't want to have to make everyone do: `<Modal><Modal.Dialog>...</Modal.Dialog></Modal>` to use it, but maybe that's ultimately the best way to go?

**Comment by mfunkie** [comment]
I like the idea behind this.  Basically separating the driver of the Modal from the Modal's Markup, correct?  I think it's moving closer to bringing a lot of value to people who might not even use Bootstrap, but want a lot of the functionality that this library provides.

**Comment by taion** [comment]
@jquense 

I feel like a prop is the best way to handle this - child sniffing seems really dangerous and trouble-prone.

I think it'd be reasonable to have a `customModal` prop that defaults to `false` that controls this. I'd be okay with requiring `ModalDialog` going forward as well. Don't feel strongly either way.

**Comment by jquense** [comment]
Appveyor being a doofus again...

I added `dialogComponent` as a prop that should solve most of the need in that regard I think, I also updated the classes to use bsClass directly so that will be changeable by folks who need to separate out the styles. I think we are gtg if anyone can take a peak

**Comment by taion** [comment]
Cool - so the idea is that the API would look like `<Modal dialogComponent={MyModalDialog} ...`?

@mfunkie How does this look to you?

**Comment by jquense** [comment]
Ya exactly. if you don't want to add a new wrapping element changing the default you can also do something like: 

```js
Object.assign(Modal.defaultProps, {
  dialogComponent: MyCoolDialog,
  bsClass: 'my-modal'
})
```

or whatever

**Comment by mfunkie** [comment]
Since you're kinda merging props with the dialogComponent, can you allow className to be passed also?  It doesn't look like you're using that prop and it would get overwritten if I remember right (className doesnt get merged in prop spread right?)

**Comment by taion** [comment]
I guess the alternative would be something like

```js
<Modal customDialog={true} /* ... */>
  <MyModalDialog />
</Modal>
```

I dunno if that's any good.

**Comment by jquense** [comment]
@mfunkie in this case you aren't passing `dialogComponent` an Element but a class, so merging classnames would be the responsibility of MyCoolDialog

**Comment by jquense** [comment]
Backed the dialog API out for now, so we can get a release out. will open a new PR to bike shed the api a bit more

**Comment by taion** [comment]
LGTM

**Pull request merged**
