### PR TITLE
Add toggle button components

### PR DESCRIPTION
**Pull request by jquense**
I’m tried of rewriting this component all the time :P

### CODE REVIEW

**Comment by taion** [comment]
ref https://github.com/react-bootstrap/react-bootstrap/issues/1587

**Comment by taion** [comment]
Is it really better to have `<ToggleButton>` rather than some sort of styling props for `<Checkbox>` and `<Radio>`? The actual markup for the buttons seems almost identical to that for inline checkboxes and radios – just the CSS classes are different.

**Comment by jquense** [comment]
I should not that the API here differs from upstream, in that it's more restrictive. here you must provide a `value` to the children which i also use like `eventKey`...I'm not at all sure why you would want radio/checkbox groups with no values but upstream does allow it.

**Comment by jquense** [comment]
> Is it really better to have <ToggleButton> rather than some sort of styling props for <Checkbox> and <Radio>?

I don't know, do you think it's clear to add the button classes to those components/ remove the existing classes?

**Comment by taion** [comment]
I dunno. The other bit is that we took out `<RadioGroup>`, so it's a bit odd to have group-style management here only in the context of toggle buttons.

We could add it back if it's a useful primitive even when using e.g. React-Formal and Redux Form, though, but it probably shouldn't be an "only-for-toggle-buttons" thing.

**Comment by jquense** [comment]
The problem with the Group components is the dang styling that is sort of intractable. I agree though that it's odd to have one and not the other, _except_ that twbs doesn't have a RadioGroup component specifically.

I don't honestly really understand what the point of this component is in the context of React. Like is the checkbox/radio inputs bit more of an implementation detail that lets you do some native state tracking or is this styling for these form inputs? Personally I don't need the form wrapping bit, but I didn't want to jsut remove it lots of ppl seems to still use normal html forms with React :p

**Comment by drsloth** [comment]
Hey all, where would you say the process is to get this implemented? This is exactly what I have need for

**Comment by jquense** [comment]
> Hey all, where would you say the process is to get this implemented?

if by "this" you mean the toggle buttons, i've mostly implemented, it just needs tests

**Comment by taion** [comment]
@jquense 

I think we can re-use the logic in `<Checkbox>` and `<Radio>`. At a glance, these render correctly:

```js
<Button componentClass={Checkbox} bsStyle="primary" inline active>Left</Button>
```

The other thing, I see that the actual button components in our context have to be controlled because `.active` has to get attached to the `label`.

However, given that, I think it'd make more sense to have the "group" component be generic, and have the `<ButtonGroup>` version just be a special case there.

Also, for checkboxes it should probably be an object rather than an array.

**Comment by taion** [comment]
IOW, this look right:

```js
<ButtonGroup data-toggle="buttons">
  <Button componentClass={Checkbox} bsStyle="primary" inline active>Left</Button>
  <Button componentClass={Checkbox} bsStyle="primary" inline>Middle</Button>
  <Button componentClass={Checkbox} bsStyle="primary" inline>Right</Button>
</ButtonGroup>
```

but obviously doesn't work.

**Comment by jquense** [comment]
The problem with that is you get a bunch of checkbox classes that shouldn't be added.

I think it makes sense to roll it into ButtonGroup.

> Also, for checkboxes it should probably be an object rather than an array.

not sure what you mean by that, like the value, what would be the key/value?

**Comment by taion** [comment]
`<ButtonGroup>` feels weird because the core of the logic is not button-specific at all.

For checkboxes, I think it ought to be `{[eventKey]: bool}`... with the limitation that eventKeys are all strings, I guess.

**Comment by jquense** [comment]
putting aside the wonkiness of this whole component for second, upstream has it has "part of th buttonGroup" so that makes sense in my head.

For checkbox values, I think it has to an array of the checkbox values, that's usually how like named checkboxes are traditionally serialized in forms (e.g. jquery will give you the array). It's like a multiselect sort of thing. Admittedly there is a tension between that and unnamed checkboxes, which wouldn't work here. However i'd suggest that this component makes no sense as a form input without named checkboxes.

**Comment by jquense** [comment]
or rather if we treat it like a multiselect, vs a collection of checked things, its more useful in other contexts i think, like react-formal ;)

**Comment by taion** [comment]
Well, okay, if other places do the array of values...

I guess is the idea that, in the general case, there's not much point to the non-presentational bits of the "group" logic here?

**Comment by taion** [comment]
This LGTM net of tests. Should we add http://getbootstrap.com/javascript/#buttons-single-toggle as well?

**Comment by jquense** [comment]
>  Should we add http://getbootstrap.com/javascript/#buttons-single-toggle as well?

Maybe the ToggleButton here covers that? Should I call this CheckboxButton and make ToggleButton the none input version? Might be confusing for folks i dunno

**Comment by taion** [comment]
I dunno.

**Comment by jquense** [comment]
I say leave off the single toggle for now since it's Essentially just a button with an active prop and aria-pressed. I'll add tests here also

**Comment by taion** [comment]
Sounds good.

**Comment by jquense** [comment]
updated and should be good. Who knows what codecov's deal is

**Comment by taion** [comment]
@jquense Err what happened to the tests here?

**Comment by jquense** [comment]
wtf?!?

**Comment by taion** [comment]
They got lost?

**Pull request merged**
