### PR TITLE
Fix(Bs3): Remove unsafe lifecycles by upgrading react-overlays to ^1.2.0

### PR DESCRIPTION
**Pull request by nortonwong**
Closes https://github.com/react-bootstrap/react-bootstrap/issues/4398.

Use `react-overlays` 1.x due to fewer breaking changes. In 2.x, **RootCloseWrapper** has been replaced by the [`useRootClose` hook](https://github.com/react-bootstrap/react-overlays/blob/v2.0.0/src/useRootClose.js). This change set should still be compatible with `react` ^16.3.0.

#### Adapt **Modal**:
* Maintain backwards-compatibility for `props.backdropClassName` and `props.backdropStyle` by using a fallback value for `props.renderBackdrop`.
* Convert **ModalDialog** into a `forwardRef`, because **BaseModal** [expects the ref to be a DOM node](https://github.com/react-bootstrap/react-overlays/blob/v1.2.0/src/Modal.js#L371).

#### Adapt **Overlay** component family:
* Take changes from master for components integrated with `react-popper`: **Overlay**, **OverlayTrigger**, **Tooltip**, and **Popover**.
* Accept breaking prop changes from master.
* Drop changes where `props.bsClass` was converted into `props.bsPrefix`, since the new utilities require [`useContext`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ThemeProvider.js#L19) and a branch-wide prop rename.
* Drop **Popover.Title** and **Popover.Content** as out of scope.

#### Adapt tests:
* Fix tests broken by using [ReactTestUtils on `forwardRef` components](https://github.com/facebook/react/issues/13455).

### CODE REVIEW

**Comment by nortonwong** [comment]
Unfortunately, `yarn run build-docs` on bs3-dev gives me
```js
ReferenceError: React is not defined
```
even without the changes in this PR.

**Comment by nortonwong** [comment]
Turns out the `raw-loader` regex wasn't cross-OS. 🤷

Because the setup didn't understand `forwardRef` components, the ModalDialog graphql result was null. I upgraded `react-docgen` past [3.0.0](https://github.com/reactjs/react-docgen/releases/tag/v3.0.0), and there were a few other failures until I bumped the `gatsby` packages.

**Comment by mturley** [comment]
@nortonwong anything I can do to help you get this merged? My team has some folks bugging us to fix lifecycle method warnings, we would love to help get the fixes released if we can.

**Comment by nortonwong** [comment]
@mturley Thanks. I'm waiting on feedback at the moment.

The code coverage has dropped for Overlay and OverlayTrigger, so if this gets merged eventually those files will need more tests. In the meantime I'm waiting for the maintainers to review this.

**Comment by nortonwong** [comment]
In the meantime, you can silence all the other warnings by using the latest from the branch in your package.json:
```js
    "react-bootstrap": "react-bootstrap/react-bootstrap#bs3-dev",
```

**Comment by wheeler** [comment]
Also interested to help if possible. Looks like this PR pulls most of its hefty changes out of the bs4 master branch. Master has approximately the same coverage so we can probably dismiss the `codecov/patch`?

@taion @jquense anything that would be helpful for review?

**Pull request closed without merging**
