### PR TITLE
fix(Modal): TypeScript manager typings

### PR DESCRIPTION
**Pull request by voidale**
The docs have a manager property but it's missing from the types

### CODE REVIEW

**Comment by taion** [comment]
Note the CI failure. Also, I think we should at least have a nominal type there for the manager.

**Comment by kosmiq** [comment]
What should the manager accept? The docs says object, so it would be enough with a type that is object?

**Comment by taion** [comment]
It should be an instance of `ModalManager` from React Overlays: https://github.com/react-bootstrap/react-bootstrap/blob/3f981a42815603a111a630c49365ab9bba81dd6f/src/BootstrapModalManager.js
https://github.com/react-bootstrap/react-overlays/blob/c29dc76f66c7eb74f5123ca9d5f531918ea7134a/src/ModalManager.js

Unfortunately there are no typings for that, so... not sure what we can do

**Comment by mxschmitt** [comment]
> It should be an instance of `ModalManager` from React Overlays: [/src/BootstrapModalManager.js@`3f981a4`](https://github.com/react-bootstrap/react-bootstrap/blob/3f981a42815603a111a630c49365ab9bba81dd6f/src/BootstrapModalManager.js)
> [react-bootstrap/react-overlays:src/ModalManager.js@`c29dc76`](https://github.com/react-bootstrap/react-overlays/blob/c29dc76f66c7eb74f5123ca9d5f531918ea7134a/src/ModalManager.js)
> 
> Unfortunately there are no typings for that, so... not sure what we can do

@taion maybe for now type any?

**Comment by taion** [comment]
@mxschmitt probably, yeah! unless something like `{}` works...

**Pull request merged**
