### PR TITLE
excluding warning messages for using "Overlay" component

### PR DESCRIPTION
**Pull request by otanim**
excluding warning messages for using "Overlay" component, mainly for properties: "outOfBoundaries" and "show".

### CODE REVIEW

**Comment by taion** [comment]
can you run formatting on the code, so CI passes?

**Comment by otanim** [comment]
@taion `npm test` throws this errors:
```
> react-bootstrap@1.0.0-beta.5 test /home/hidden/react-bootstrap
> npm run lint && npm run dtslint && npm run test-browser && npm run test-node


> react-bootstrap@1.0.0-beta.5 lint /home/hidden/react-bootstrap
> npm run ci-lint .


> react-bootstrap@1.0.0-beta.5 ci-lint /home/hidden/react-bootstrap
> eslint --rule "prettier/prettier: 2" "."


/home/hidden/react-bootstrap/src/AbstractNav.js
   71:23  error  'parentOnSelect' is missing in props validation   react/prop-types
  109:7   error  'parentOnSelect' is missing in props validation   react/prop-types
  110:7   error  'getControlledId' is missing in props validation  react/prop-types
  111:7   error  'getControllerId' is missing in props validation  react/prop-types
  112:7   error  'activeKey' is missing in props validation        react/prop-types

/home/hidden/react-bootstrap/src/AbstractNavItem.js
  30:7   error  'onSelect' is missing in props validation  react/prop-types
  67:29  error  'onClick' is missing in props validation   react/prop-types

/home/hidden/react-bootstrap/src/Button.js
  78:7  error  'innerRef' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/src/ListGroupItem.js
  53:13  error  'onClick' is missing in props validation   react/prop-types
  72:7   error  'eventKey' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/src/Modal.js
  232:13  error  'manager' is missing in props validation          react/prop-types
  254:13  error  'bsPrefix' is missing in props validation         react/prop-types
  266:7   error  'bsPrefix' is missing in props validation         react/prop-types
  275:7   error  'manager' is missing in props validation          react/prop-types
  279:7   error  'onEscapeKeyDown' is missing in props validation  react/prop-types
  280:7   error  'onShow' is missing in props validation           react/prop-types
  294:7   error  'backdropStyle' is missing in props validation    react/prop-types

/home/hidden/react-bootstrap/src/NavLink.js
  68:3  error  'innerRef' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/src/OverlayTrigger.js
  199:7  error  'popperConfig' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/src/SafeAnchor.js
  73:7  error  'innerRef' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/src/ThemeProvider.js
  39:31  error  'bsPrefix' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/src/Tooltip.js
  77:3  error  'outOfBoundaries' is missing in props validation  react/prop-types

/home/hidden/react-bootstrap/www/config.js
  15:34  error  Unable to resolve path to module 'bootstrap/package.json'  import/no-unresolved

/home/hidden/react-bootstrap/www/gatsby-config.js
  2:28  error  Unable to resolve path to module 'remark-slug'                              import/no-unresolved
  3:34  error  Unable to resolve path to module 'gatsby-transformer-react-docgen/Doclets'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/Anchor.js
  4:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/Callout.js
  4:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/CodeBlock.js
  2:20  error  Unable to resolve path to module 'astroturf'                            import/no-unresolved
  3:22  error  Unable to resolve path to module 'recompose/mapProps'                   import/no-unresolved
  5:38  error  Unable to resolve path to module 'prismjs/components/prism-core'        import/no-unresolved
  6:8   error  Unable to resolve path to module 'prismjs/components/prism-clike'       import/no-unresolved
  7:8   error  Unable to resolve path to module 'prismjs/components/prism-javascript'  import/no-unresolved
  8:8   error  Unable to resolve path to module 'prismjs/components/prism-markup'      import/no-unresolved
  9:8   error  Unable to resolve path to module 'prismjs/components/prism-jsx'         import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/ComponentApi.js
   1:25  error    Unable to resolve path to module 'gatsby'           import/no-unresolved
   4:20  error    Unable to resolve path to module 'astroturf'        import/no-unresolved
  59:25  warning  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger

/home/hidden/react-bootstrap/www/src/components/Heading.js
  4:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/LinkToSource.js
  2:20  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/Main.js
  6:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/NavMain.js
  8:20  error  Unable to resolve path to module 'astroturf'            import/no-unresolved
  9:23  error  Unable to resolve path to module 'recompose/withProps'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/PropTable.js
   1:25  error  Unable to resolve path to module 'gatsby'     import/no-unresolved
  11:20  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/ReactPlayground.js
   4:29  error  Unable to resolve path to module 'astroturf'   import/no-unresolved
  10:25  error  Unable to resolve path to module 'formik'      import/no-unresolved
  18:8   error  Unable to resolve path to module 'react-live'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/SideNav.js
   7:20  error  Unable to resolve path to module 'astroturf'            import/no-unresolved
  10:23  error  Unable to resolve path to module 'recompose/withProps'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/components/Toc.js
  2:20  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/examples/Overlays/Overlay.js
  23:14  error  Replace `·placement,·scheduleUpdate,·arrowProps,·outOfBoundaries,·show,·...props` with `⏎············placement,⏎············scheduleUpdate,⏎············arrowProps,⏎············outOfBoundaries,⏎············show,⏎············...props⏎·········`  prettier/prettier
  23:71  error  'show' is already declared in the upper scope                                                                                                                                                                                                       no-shadow

/home/hidden/react-bootstrap/www/src/layouts/index.js
  1:29  error  Unable to resolve path to module '@mdx-js/tag'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/figures.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/forms.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/images.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/input-group.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/jumbotron.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/modal.js
  1:25  error  Unable to resolve path to module 'gatsby'     import/no-unresolved
  3:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/navbar.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/overlays.js
  1:25  error  Unable to resolve path to module 'gatsby'     import/no-unresolved
  3:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/pagination.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/progress.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/table.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/components/tabs.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/index.js
  7:20  error  Unable to resolve path to module 'astroturf'            import/no-unresolved
  8:23  error  Unable to resolve path to module 'recompose/withProps'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/layout/grid.js
  1:25  error  Unable to resolve path to module 'gatsby'     import/no-unresolved
  3:21  error  Unable to resolve path to module 'astroturf'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/layout/media.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/pages/utilities/responsive-embed.js
  1:25  error  Unable to resolve path to module 'gatsby'  import/no-unresolved

/home/hidden/react-bootstrap/www/src/wrap-page.js
  1:33  error  Unable to resolve path to module '@mdx-js/tag'  import/no-unresolved

✖ 74 problems (73 errors, 1 warning)
  1 error and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-bootstrap@1.0.0-beta.5 ci-lint: `eslint --rule "prettier/prettier: 2" "."`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-bootstrap@1.0.0-beta.5 ci-lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-bootstrap@1.0.0-beta.5 lint: `npm run ci-lint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-bootstrap@1.0.0-beta.5 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! Test failed.  See above for more details.
```

**Comment by taion** [comment]
see the travis output on the PR build status. i think your additional local errors might only come from certain packages not being installed

**Comment by otanim** [comment]
@taion, eslint's detection inside of JSX is happening incorrectly and error message below is not relevant:
```
23:71  error  'show' is already declared in the upper scope
```

**Comment by taion** [comment]
so you need to destructure that into another name, e.g. `show: _show`

**Comment by taion** [comment]
@jquense can you confirm the netlify failure is spurious here? if so, i think we're good to merge this

**Comment by zverexe** [comment]
I'm having same issues. Can this be fixed somehow?
react-dom.development.js:506 Warning: React does not recognize the `outOfBoundaries` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `outofboundaries` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by InnerPopper)
    in Transition (created by Fade)
    in Fade (created by InnerPopper)

react-dom.development.js:506 Warning: React does not recognize the `scheduleUpdate` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scheduleupdate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by InnerPopper)
    in Transition (created by Fade)
    in Fade (created by InnerPopper)

react-dom.development.js:506 Warning: React does not recognize the `arrowProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `arrowprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by InnerPopper)
    in Transition (created by Fade)
    in Fade (created by InnerPopper)

**Comment by otanim** [comment]
@zverexe , I've already provided fixed version in this pull request, check file changes. I hope this pull request will be approved soon.

**Comment by otanim** [comment]
@taion, @jquense any updates on this?

**Pull request merged**
