### PR TITLE
fix(Modal): Fix wrong types on ModalProps

### PR DESCRIPTION
**Pull request by kyletsang**
Backport modal props fix from master to v4

### CODE REVIEW

**Comment by ckruse** [comment]
Did this introduce a new bug? Now modals don't seem to work anymore. Given this code:

```
        <Modal show={true} size="lg" backdrop="static" animation={false}>
          <Modal.Header>
            <Modal.Title>{details.subject}</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            {/* ... */}
          </Modal.Body>
        </Modal>
```

I get this message:

```
Type '{ children: Element[]; show: true; size: "lg"; backdrop: "static"; animation: false; }' is not assignable to type 'ModalProps'.
  Types of property 'children' are incompatible.
    Type 'Element[]' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>': type, props, key  TS2322

    55 |
  > 56 |         <Modal show={true} size="lg" backdrop="static" animation={false}>
       |          ^
    57 |           <Modal.Header>
    58 |             <Modal.Title>{details.subject}</Modal.Title>
    59 |           </Modal.Header>
```

**Comment by kyletsang** [comment]
@ckruse sorry, looks like there was a part 2 PR for this that I missed.  Will republish shortly

**Comment by ckruse** [comment]
Thank you!

**Comment by kyletsang** [comment]
@ckruse 1.6.3 is published.  Thanks for reporting the bug 👍

**Comment by ckruse** [comment]
Can confirm, it is fixed. thank you very much!

**Pull request merged**
