### PR TITLE
Improve tabs accessibility

### PR DESCRIPTION
**Pull request by matt-royal**
Add role="tablist" to the nav inside of tabs. Also backfill a test for adding aria-selected to the nav item for the currently active tab.

The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella

### CODE REVIEW

**Comment by jquense** [comment]
LGTM, can you squash and set the commit message according to the guidelines here: https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md#commit-subjects-for-public-api-changes

**Comment by taion** [comment]
LGTM as well once squashed.

**Comment by matt-royal** [comment]
@jquense We can definitely squash the commits together. Since we don't think we changed any APIs in this PR, we're unsure of what changes you'd like to see in the commit message. Could you please clarify?

**Comment by taion** [comment]
It should be `[changed]` because of the (very minor) change to what the public API does.

**Comment by matt-royal** [comment]
Thanks, @talon. Please let us know if the new commit message isn't what you had in mind.

**Comment by taion** [comment]
Oh `[added]` is fine too.

**Comment by jquense** [comment]
That looks great! Changing ARIA affects the interactions for SR users so its fair to consider it an "api change" in general we are pretty broad on that definition anyway.

**Pull request merged**
