### PR TITLE
fix(Tabs): fix transition functions

### PR DESCRIPTION
**Pull request by golota60**
While poking around in `Tab` component, I've noticed that none of the react-transition-group functions work (`onEnter, onExit etc.`). This was because in `useTabPanel` hook we expose them in the first argument, not the second one (https://github.com/react-restart/ui/blob/c6f9e22dd0cfcef412d3d00618aa5ec453f63bb6/src/TabPanel.tsx#L88).

 This PR moves all of these functions to the correct position. Also added a test for it

### CODE REVIEW

**Comment by kyletsang** [comment]
Nice catch.  We should actually fix this in `@restart/ui`.  I meant to put the transition callback props into the hook's metadata return, not the first.

**Comment by golota60** [comment]
alright! will create a PR in restart/ui shortly

**Comment by golota60** [comment]
done - do we want to keep a test in here too or will the one in `restart/ui` be enough?

**Comment by kyletsang** [comment]
> done - do we want to keep a test in here too or will the one in `restart/ui` be enough?

I think the tests in restart/ui is good enough 👍 

Thanks for making those changes!

**Comment by golota60** [comment]
no problem! glad i can help

**Pull request closed without merging**
