### PR TITLE
getValue() should return all selected options for multiple select

### PR DESCRIPTION
**Pull request by heydiplo**

### CODE REVIEW

**Comment by mtscout6** [comment]
LGTM

**Comment by trentgrover-wf** [comment]
+1
might be nice to have example usage in the docs site

**Comment by mtscout6** [comment]
Somewhat related to #342

**Comment by heydiplo** [comment]
@trentgrover-wf, example of multiple select is already in place, and the fact getValue() returns an array seems anticipated. Do you think we should explicitly state it?

@mtscout6, I like the idea of distinct inputs a lot, I think it would be much more natural. But it seems to be a big change that would take some time to implement. This fix, in turn, is simple, and someone can use it right now. And it can be just transferred to <Select /> later.

**Comment by mtscout6** [comment]
@heydiplo I agree that it can come in here and let #342 move it later. Can you add something to the docs to reflect this before we bring it in?

**Comment by heydiplo** [comment]
@mtscout6, sure, added it to the Input Types section.

**Comment by mtscout6** [comment]
Gotcha, thanks for the heads up.

**Pull request merged**
