### PR TITLE
Fix for a responsive and collapsive navbar on item select event

### LINKED ISSUE #1301: Add option to collapse Navbar when item is selected
How do you make the menu collapse after item is selected?

    import React from 'react';
    import {Navbar, Nav, NavItem, NavDropdown, DropdownButton, MenuItem, CollapsibleNav} from 'react-bootstrap';

    export default class App extends React.Component {

    constructor(props) {
      super(props);
      this.onSelect = this.onSelect.bind(this);
      this.toggleNav = this.toggleNav.bind(this);
      // this.state = {navExpanded: false};
    }

    onSelect(e){
        console.log('OnSelect')
        // console.log(this.state.navExpanded);
        // this.setState({navExpanded: false});
    }

    toggleNav(){console.log('toggle...')};

    // <Navbar inverse fixedTop toggleNavKey={0} navExpanded={this.state.navExpanded} onToggle={() => this.toggleNav()}>
    // <Navbar inverse fixedTop toggleNavKey={0} navExpanded={this.state.navExpanded} >

    render() {
        return (

          <Navbar inverse fixedTop toggleNavKey={0} >
            <Nav right eventKey={0} onSelect={this.onSelect} > {/* This is the eventKey referenced */}
              <NavItem eventKey={1} href="#">Link</NavItem>
              <NavItem eventKey={2} href="#">Link</NavItem>
            </Nav>
          </Navbar>     

      )

    }

    componentDidMount() {

    }
    }

    React.render(<App />, document.getElementById('example'));

### PR DESCRIPTION
**Pull request by zirho**
This is not perfect since dropdown menu in nav not collapsing all the way up to main nav but hope this help for someone to use or continue to fix this issue
fix #1301

### CODE REVIEW

**Comment by taion** [comment]
Implementation concerns aside (and there are those), we don't want this to be the default behavior – upstream TWBS doesn't work this way.

**Comment by taion** [comment]
The right API here is to give `NavItem` something like a prop that opts into this behavior on the `NavItem` level.

**Comment by zirho** [comment]
To make clicking NavItems collapse NavbarCollapse, put "autoCollapse"
attribute on NavbarCollapse or directly to NavItems to overwrite the
behavior.
or just simply put it on only one NavItem to collapse Navbar.

**Comment by taion** [comment]
It stands for Twitter Bootstrap.

**Comment by zirho** [comment]
I found something wrong in action.
Hold this for a moment 

thanks

**Comment by olalonde** [comment]
+1, also need this, can we merge :)

@taion Not sure it's fair to say TWBS doesn't work this way as TWBS nav links are not typically intercepted in Javascript and to the user, it looks as if the menu collapsed after clicking a link. I'm fine if it's an optional attribute though.

**Comment by jquense** [comment]
OK the diff here is a bit of a mess so its tough to see what's going one but I don't think this is the right approach...

If I was writing this I think I would not worry about "auto collapsing" at all and just make sure to surface any onSelect events from Nav's or Dropdown's up to the Navbar, then the user can decide to do whatever they want with that, such as toggling the collapse. 

My problem with codifying this behavior as a feature is that we can't reasonably cover all the general cases you'd want the navbar to collapse, like Buttons...actually this is fairly straightforward to do in user land I think we should just stay out entirely.

```jsx
render() {
  return (
    <Navbar 
       expanded={this.state.expanded}
       onToggle={expanded => this.setState({ expanded })}
    >
      <Nav onSelect={() => this.setState({ expanded: false })}>
         {/* whatever */}
      </Nav>
    </Navbar>
  )
}
```

**Comment by zirho** [comment]
Hi, Thanks for all feedbacks.

@jquense I tried to apply your approach on react-tutorial. (using CDNs)
Here is the code that I was working, but I couldn't make it work. (it may be due to lack of basic for react)
https://github.com/reactjs/react-tutorial
Can you advise me to make this work, if it's not too much trouble? or anybody?
I'd be very much appreciated if you can.

Thank you in advance.

**Comment by taion** [comment]
@jquense Do you think there's any value in having a simplified version for the case where the navbar only contains links?

**Comment by jquense** [comment]
perhaps? I am worried about the complication tho, and "contexting all the things" adding too much hidden complexity. 

in this case I'd be worried that there will be to many edge cases and we'll get issues about it. I don't feel super strongly tho, especially since I don't tend to need this behavior. what do you think?

**Comment by taion** [comment]
I'd probably use this feature if it were available.

At a guess, most users of `<Navbar>` probably use it in a very simple form with just plain `<NavItem>`s, so in practice this should give users a good way to get what they need.

**Comment by olalonde** [comment]
I'm not sure I understand what the work around is. I tried setting collapsed attribute on my NavBar but once the toggle is pushed once, it ignores the collapsed attribute.

**Comment by abloomston** [comment]
I found @jquense user land implementation to work fine for me. I would, however, find it quite useful to have that implementation available via simply setting a prop.

**Comment by zirho** [comment]
@abloomston Can you please give a link to it?

thanks

**Comment by abloomston** [comment]
@zirho here is the commit where I used @jquense user land implementation: https://github.com/abloomston/learning-bootstrap-3/commit/275940373d3877ece2c3e4851ee117cdccb000a3

**Comment by zirho** [comment]
@abloomston Thank you!

**Comment by taion** [comment]
Replaced by https://github.com/react-bootstrap/react-bootstrap/pull/2280

**Pull request closed without merging**
