### PR TITLE
[FEATURE] Added ability for multiple panels to expand

### PR DESCRIPTION
**Pull request by gfunk1230**
Configured accordion to be able to open multiple panels on click. Please see gif for example.

_Credits: @rovolution_ & Myself.

react-bootstrap-multipanel

### CODE REVIEW

**Comment by jquense** [comment]
hey there! Thanks for the PR! I think we may not need to add an additional prop here for a few reasons.  First the panel API is changing fairly dramatically in the next version so this may not translate, second It's a bit confusing to call something an accordian but then have it not act like one (one open at a time). Finally tho you can actually already do this, without any changes!

```
<PanelGroup defaultActiveKey="2">
    <Panel collapsible header="Panel 1" eventKey="1">Panel 1 content</Panel>
    <Panel collapsible header="Panel 2" eventKey="2">Panel 2 content</Panel>
  </PanelGroup>
```

**Comment by taion** [comment]
What @jquense said.

Although you don't need the `defaultActiveKey` prop I think?

**Comment by gfunk1230** [comment]
Thanks, You guys were right but maybe we could update your documentation with an example of this use case. I didn't realize I had to use a PanelGroup.

**Comment by jquense** [comment]
If you want to support a docs PR adding an example we'll be happy to merge it :)

**Comment by taion** [comment]
BTW, I don't think you technically _need_ `<PanelGroup>`. In this context, `<PanelGroup>` is just a `<div className="panel-group">`. You just need to not set `accordion` on the `<PanelGroup>`.

**Comment by jquense** [comment]
i want to say the panel-group adds some margins but i don't actually know that

**Pull request closed without merging**
