### PR TITLE
Rename <PageItem> to <Pager.Item>

### PR DESCRIPTION
**Pull request by MattCain**
Addresses issue #1757 

Renaming the file from PageItem.js to PagerItem.js is a breaking change so I'm submitting this against the next branch as it says to in CONTRIBUTING.md.

Hopefully I did the PR right this time 😄

Let me know if i've got anything wrong, happy to fix things quickly.

Thanks

### CODE REVIEW

**Comment by taion** [comment]
The code looks good.

Can you rebase this PR? The `next` branch was unfortunately quite stale since we hadn't pushed anything to it in a while.

**Comment by taion** [comment]
(As in it was quite a ways behind `master`)

**Comment by MattCain** [comment]
Hi @taion, I just did the rebase, I haven't done many rebases before so let me know if i've missed anything. Thanks

**Comment by taion** [comment]
LGTM

**Comment by taion** [comment]
@react-bootstrap/collaborators Can we merge this?

**Pull request merged**
