### PR TITLE
Update ESLint to 0.21.2

### PR DESCRIPTION
**Pull request by mtscout6**

### CODE REVIEW

**Comment by dozoisch** [comment]
if the test passes LGTM, though I prefer using `~0.21.2` instead of `^0.21.2` because `^` is a bit greedy.

**Comment by taion** [comment]
It's the same for anything v0. And I added test cases to eslint with my PR, so this use case hopefully won't break again in the same way.

**Comment by mtscout6** [comment]
For pre 1.0 packages `~` and `^` make no difference. See: http://semver.npmjs.com/

**Comment by dozoisch** [comment]
@mtscout6 oh wow didn't know that!

**Comment by taion** [comment]
LGTM

**Pull request merged**
