### PR TITLE
switch to new one

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by hjanuschka** [comment]
@taion can you please publish a new release

**Comment by taion** [comment]
This PR should make almost no difference to end users.

**Comment by hjanuschka** [comment]
@taion  but it should remove the warning: `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`  or am i wrong?

**Comment by taion** [comment]
That has nothing to do with this.

**Comment by jquense** [comment]
This doesn't fix any warnings just changes the name of a package. Those warnings are from something else

**Comment by hjanuschka** [comment]
exception is from: react-overlays Transition.js:259
```
Transition.propTypes = {
  /**
   * Show the component; triggers the enter or exit animation
   */
  in: _react2.default.PropTypes.bool,
```

any advises on how to solve it?

**Comment by hjanuschka** [comment]
maybe this PR?: https://github.com/react-bootstrap/react-overlays/pull/166

**Pull request merged**
