### PR TITLE
[removed] Don't need to disable Babel cache

### PR DESCRIPTION
**Pull request by taion**
Superseded by babel-loader#5.2.0

### CODE REVIEW

**Comment by taion** [comment]
Note that this takes out the custom cache directory as well, since developers on the correct version of `babel-loader` won't even need to explicitly clear their cache during development.

**Comment by mtscout6** [comment]
Dependent on #896?

**Comment by taion** [comment]
This is on the alpha branch while #896 is on master, so hopefully shouldn't be relevant.

**Comment by AlexKVal** [comment]
I'll fix eslint warnings by next commit.

**Pull request merged**
