### PR TITLE
[added] Allow custom Modal dialog components

### PR DESCRIPTION
**Pull request by jquense**
pulled out from #1040, needs some additional bike shedding 

cc @mfunkie

### CODE REVIEW

**Comment by taion** [comment]
Reprise - the question to me is whether we like the current API better, or if it would be better to do e.g.

```js
<Modal customDialog={true} ... >
  <MyModalDialog />
</Modal>
```

**Comment by AlexKVal** [comment]
I vote for @taion proposal:
```js
<Modal customDialog={true} ... >
  <MyModalDialog />
</Modal>
```

I'm proposing the same API for another issue: https://github.com/react-bootstrap/react-bootstrap/pull/1071

**Comment by AlexKVal** [comment]
Matt also is a proponent of such API :smile:  https://github.com/react-bootstrap/react-bootstrap/issues/748#issuecomment-108510673

**Comment by taion** [comment]
I retract what I said earlier.

For handling the "generic modal" use case, it makes more sense to split out a new package from this with the core utilities around e.g. `Modal`, `Overlay`, `Transition`, `Position`, and friends.

It makes more sense for the `Modal` component in React-Bootstrap itself to map well to the Bootstrap modal, which this accomplishes quite well, while still giving some flexibility for customization.

I'm okay with merging this as-is. Will open a new issue regarding pulling out core components.

**Comment by taion** [comment]
@jquense Can you rebase this? Let's merge this and defer the generic API to #1084, unless there are further objections.

**Comment by taion** [comment]
I rebased - the conflict was spurious (some overlapping lines with another added test).

**Comment by jquense** [comment]
I am fine with this as is if you are.

**Pull request merged**
