### PR TITLE
[added] utils namespace

### PR DESCRIPTION
**Pull request by tomatau**
Exposes `domUtils`, `CustomPropTypes` and other useful utilities.

Original PR here https://github.com/react-bootstrap/react-bootstrap/pull/745

This has a nicer commit history

### CODE REVIEW

**Comment by taion** [comment]
I think we still need this merged as 1 commit rather than 2?

**Comment by tomatau** [comment]
Can you squash after pushing to a remote? What's wrong with 2 commits?

**Comment by taion** [comment]
Squash and `push -f`. I think our changelog generation wants one commit per PR.

**Comment by tomatau** [comment]
Done

**Comment by mtscout6** [comment]
LGTM

**Comment by aabenoja** [comment]
:shipit:

**Pull request merged**
