### PR TITLE
Export the DropdownItem from index

### PR DESCRIPTION
**Pull request by GabrielNicolasAvellaneda**

### CODE REVIEW

**Comment by taion** [comment]
do we really want this instead of `Dropdown.Item`?

**Comment by GabrielNicolasAvellaneda** [comment]
I don't know but other components follows this method and are exported from index so you could import many components at once:
`import { Nav, NavDropdown, Navbar, NavItem, DropdownItem } from 'react-bootstrap';`

**Comment by taion** [comment]
@jquense i defer to you here; should we do this?

**Comment by kt3k** [comment]
The migration guide seems implying this exists. 

I also found the comment (https://github.com/react-bootstrap/react-bootstrap/pull/3364#discussion_r232273723) which seems saying DropdownItem should be exported as DropdownItem as well.

**Pull request merged**
