### PR TITLE
Overlays should stay shown when we hover over them

### PR DESCRIPTION
**Pull request by dustingetz**
HI guys, I don't expect you to accept this PR, because I know regular bootstrap forbids this behavior. I am just leaving this here as documentation for the next person.

Do you have any suggestions for how I might implement this that would not require modifying react-bootstrap?

### CODE REVIEW

**Comment by taion** [comment]
You'd use `<Overlay>` directly instead of `<OverlayTrigger>`.

**Comment by dustingetz** [comment]
Is there a way to avoid copy/pasting all 294 lines of OverlayTrigger to add three lines? I tried to monkey patch but I couln't get it to work, maybe you guys have seen some tricks I can use?

**Comment by taion** [comment]
Just don't do it – look at the components page example that's tailored to the specific use case.

**Comment by dustingetz** [comment]
Forgive me, but which quote are you referring to? "It's inadvisable to use "hover" or "focus" triggers for popovers, because they have poor accessibility" ? or " Creating custom overlays is as easy as wrapping some markup in an Overlay component"?

I understand how to use Overlay, but I also want all the behaviors in the OverlayTrigger abstraction, with my small patch to the hover behavior.

**Comment by taion** [comment]
This section - http://react-bootstrap.github.io/components.html#custom-overlays. If you just use what's specific to your "hover" use case, it's quite a lot simpler - just track the enter/leave events you want. `<OverlayTrigger>` is intended to mimic the TWBS API, which is why we keep the meaning of "hover" (e.g. what you have is mostly not appropriate for something like a tooltip).

**Comment by mezod** [comment]
hey @dustingetz did you manage to pull this behaviour in a nice way? i'd be interested to see how to do it without copying the complete OverlayTrigger into my project, thanks!

**Comment by dustingetz** [comment]
Yes, I am happily running with the commit attached to this pull request

**Comment by mezod** [comment]
you created a new OverlayTrigger into your project and changed the paths or?

**Comment by mezod** [comment]
got it working that way, but feels clunky :p

**Pull request closed without merging**
