### PR TITLE
WIP: V4 support

### PR DESCRIPTION
**Pull request by jquense**
This is very very very WIP, not likely to be merged soon. Since v4 is now in beta it seems like a good time to start exploring updates here in RB. 

I’ve set up a storybook to track the components visually and confirm stuff is matching the upstream docs. Its very informal (a checkmark in the description) but Should leave us with a good sense of progress at least initially

- [x] buttons
- [x] transitions
- [ ] dropdowns
- [ ] cards
- [x] labels/badges
- [x] tables
- [ ] tabs/pills
- [ ] nav
- [ ] navbar
...more things

### CODE REVIEW

**Comment by taion** [comment]
What do you think we should do here, BTW? Break things and support only v4, or move the v3 stuff into a subdirectory?

**Comment by jquense** [comment]
I think we finish and call v1 on what we have. e.g. one more < 1.0.0 version to collect some feedback on the panel and paginattion changes and then v1

then v2 for v4. We can keep the v1 branch around for bugfixes etc, and keep pushing releases. I think it'll still be months before v4 hits stable, so i'm not super worried. And the v1 for us is really a formality, this has been a very stable package for many months now.

**Comment by leoi11** [comment]
Hi,

We're currently using reactstrap in our production app.
Totally out of curiosity, do you foresee any reasons/benefits to prefer this over reactstrap in the future?

**Comment by jquense** [comment]
I'm not super familiar with that project but I can speak to what RB is good at. We care about upgrade paths and stability since maintainers all depend on this code for production use. We also care about providing good idiomatic react APIs over bootstrap as well as provide top-notch a11y defaults as well

**Comment by changLiuUNSW** [comment]
@leoi11
The accessibility and APIs of react-bootstrap is way way better than reactstrap

**Comment by leoi11** [comment]
@changLiuUNSW Thanks for the info. Could you elaborate more on how the APIs is way better? I had a glance at the API, and they seem pretty close to each other other than some naming differences and some (doesn't seem to be a lot) extra callbacks on certain components.

**Comment by lednhatkhanh** [comment]
V4 has been officially released today.

**Comment by gaspaio** [comment]
Is work on this stopped ?

**Comment by jquense** [comment]
ya'll i'm going to close this PR and jsut make this the "base" branch for individual PR's adding support, Track the project, and individual issues for v4 progress

**Comment by wolfgangmeyers** [comment]
https://react-bootstrap.github.io/ still refers to this PR

**Comment by makhnatkin** [comment]
@jquense Hello!
Could you imagine how long it will take the transition to Bootstrap 4? We're using your project, but we're looking at others (https://reactstrap.github.io/). To make a decision to stay on your project or go to another we need to understand the timing of the implementation of version 4.

 I understand that you are doing this with your enthusiasm and thank you for this! But still it is important for us to understand how the project will develop in future

**Comment by jquense** [comment]
I don't have a specific time in mind,but you can look at the projects tab to get a sense of the rate and progress towards v4 support

**Comment by holmrenser** [comment]
https://react-bootstrap.github.io/ still refers to this PR

**Comment by m4rii0** [comment]
https://react-bootstrap.github.io/ still refers to this PR

**Comment by rafaell-lycan** [comment]
Currently I'm using the https://reactstrap.github.io/ and it's working just fine with the Bootstrap 4.

**Comment by doniyor2109** [comment]
Is there any news in this PR or we should use  https://reactstrap.github.io/ ?

**Comment by jquense** [comment]
@doniyor2109 please read the issue: https://github.com/react-bootstrap/react-bootstrap/pull/2752#issuecomment-370468335

**Comment by SachaG** [comment]
Is there a guide on how to start using the next version even if it's incomplete? It might help drive people to contribute if they can already start using it?

**Comment by holmrenser** [comment]
https://react-bootstrap.github.io/ still refers to this PR

**Comment by pedrofurtado** [comment]
@jquense Any news?

**Comment by jquense** [comment]
@pedrofurtado https://github.com/react-bootstrap/react-bootstrap/pull/2752#issue-135342585

**Pull request closed without merging**
