### PR TITLE
(fix): remove associated aria on overlay hide

### PR DESCRIPTION
**Pull request by ocBruno**
fix for issue #4934 

solution:
-get target from element during onHide event and use removeAttribute

First PR for this repo and still need to dive more into react so please spot me on any mistakes or incorrect design patterns!
Any feedback and constructive critcism is always welcome!

### CODE REVIEW

**Comment by taion** [comment]
sorry, what i mean is – it looks like popper itself gives us a way to create and clean up side effects from modifiers: https://popper.js.org/docs/v2/modifiers/#effect

given this, can we use this functionality?

**Comment by ocBruno** [comment]
> sorry, what i mean is – it looks like popper itself gives us a way to create and clean up side effects from modifiers: https://popper.js.org/docs/v2/modifiers/#effect
> 
> given this, can we use this functionality?

I think we could use this functionality if it was to improve performance but I don't know if it would, it would be nice if someone with more knowledge could chime in on this for us, any changes I'm willing to apply!

**Comment by tragessere** [comment]
@taion I don't think that cleanup function is available to here since react-bootstrap is using Popper v1.16 and not v2.x. The latest update of [react-overlays](https://github.com/react-bootstrap/react-overlays/blob/master/package.json) is still using popper v1.15 as well.

https://popper.js.org/docs/v1/
I'm not immediately seeing a good cleanup function provided in the first version.

Not sure if upgrading this library should be another task before this one.

**Comment by tragessere** [comment]
Actually I do see that there is a pull request in React-Overlays to upgrade to Popper v2. I'll just add a link here since this will probably wait on that one.

https://github.com/react-bootstrap/react-overlays/pull/766

**Comment by taion** [comment]
looks like this will be handled by https://github.com/react-bootstrap/react-bootstrap/pull/5017/files?utf8=%E2%9C%93&diff=split&w=1#diff-0d27b0102f68505cf339e89dfe5c6893R198-R202

**Comment by jquense** [comment]
thanks for this! I rolled it into #5017

**Pull request closed without merging**
