### PR TITLE
Add link for new logo survey

### PR DESCRIPTION
**Pull request by mtscout6**
Our design team has come up with a few logos that are favicon friendly. I'd like to put it up to an anonymous vote for a week and see what comes of it. Thoughts?

https://www.surveymonkey.com/s/X7Q9VX7

### CODE REVIEW

**Comment by mathieumg** [comment]
I like the last one (React colors, yay!) but think it needs improving. In the spirit of the original logo, perhaps the B could use the Bootstrap purple it used to have? Also, it seems the B is not the same as Bootstrap's, its not as bold as it should be.

**Comment by AlexKVal** [comment]
3 or 4 would do.
1 and 2 contains lines that will not bee seen in small icon IMHO.

`The great things are the simplest one` (Internet)

And it would be nice to assess small icon versions for toolbars.

**Comment by mtscout6** [comment]
The survey results are in:

screen shot 2015-05-20 at 5 59 56 pm

I couldn't export them with the free plan of survey monkey, so a screen shot will have to do.

The winner:

screen shot 2015-05-19 at 2 29 44 pm

I will be updating this on the site shortly.

**Comment by dozoisch** [comment]
:+1:

**Comment by mathieumg** [comment]
So this is set in stone and not open to discussion? :grin: (See my message above)

**Comment by mtscout6** [comment]
I was going to talk to my design guys about it today.

**Pull request merged**
