### PR TITLE
[fixed] Position.js typo `componentDidUpate`

### PR DESCRIPTION
**Pull request by ncnlinh**
Didn't spot this last time... I'm sure that all typos here are fixed already :P

### CODE REVIEW

**Comment by jquense** [comment]
Oof thanks. that's embarrassing set of typos even for me :) thanks for fixing em.

**Comment by AlexKVal** [comment]
The last time I missed to ask you @ncnlinh to change the commit message according to [Contributing Guide](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) :blush: 

Could you please change the commit's header into 
`[fixed] Position.js typo 'componentDidUpate'` ?

**Comment by ncnlinh** [comment]
@AlexKVal sure, done :+1: I'm learning to do all of this anyway so thanks a lot! :)

**Comment by ncnlinh** [comment]
@AlexKVal done :+1: I'm still learning so thanks for the help ^_^

**Comment by AlexKVal** [comment]
No no... Thanks to you for digging into and catching up these bugs :sparkle: :sparkle: 
in the new code that has been commited without tests (cough.. collaborators cough...) :smiling_imp: 

About writing the right commit messages.. you can re-wind to my first commits to this project :smile: 
They are all with exactly same problems :blush: 
And I'm learning too :wink: 

A small part of all developers contributes to OSS.
And what I've learned so far, that far less part of that part does it "right" at the beginning..
So it is OK :rainbow: 

If you will continue do OSS you will learn fast. :rocket: 
OSS is definitely the best school available :wink: 

Thank you again for your fixes :cherries:

**Pull request merged**
