### PR TITLE
docs: Remove link to nonexistent popover docs page

### PR DESCRIPTION
**Pull request by taion**
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/5214

### CODE REVIEW

**Comment by taion** [comment]
@jquense Could this be an issue with our build or Netlify config? They don't work on there.

**Comment by jquense** [comment]
They work as client navigation...i'm not sure what is required tho to make them work as actual nav? maybe we need to include a dummy page for them

**Comment by taion** [comment]
Ah, okay, let's do that instead... you mean just make any sort of dummy page just so Netlify displays something?

**Comment by bpas247** [comment]
@taion Should go ahead and close this PR?

**Comment by taion** [comment]
Do you want to make an issue to fix the generated docs, then?

**Comment by taion** [comment]
oh oops

**Pull request closed without merging**
