### PR TITLE
Use .babelrc for babel configuration

### PR DESCRIPTION
**Pull request by mtscout6**
This will allow us to configure babel in one central location from now
on. Prior to this any time we ran a babel compile, babel-loader, or
babel-node we had to configure them individually which can be error
prone in the long run.

### CODE REVIEW

**Comment by AlexKVal** [comment]
Nice :+1: 

We are already excluding `node_module` [here](https://github.com/react-bootstrap/react-bootstrap/pull/621/files#diff-e56633f72ecc521128b3db6586074d2cR6)
and it seems excluding them [here](https://github.com/react-bootstrap/react-bootstrap/pull/621/files#diff-28b51d16260380d9fae7857a4ba6dbeaR48
) is superfluous

I've tested it all without `exclude: /node_modules/`
all is green
npm run docs OK
./tools/reslease OK

**Comment by AlexKVal** [comment]
As it turned out... 
this is superfluous also [["node_modules/\*\*/*"]](https://github.com/react-bootstrap/react-bootstrap/pull/621/files#diff-e56633f72ecc521128b3db6586074d2cR6)
`babel-node` ignores `node_modules` by default.
here https://babeljs.io/docs/usage/cli/
I've checked it.

**Comment by dozoisch** [comment]
lgtm

**Comment by mtscout6** [comment]
Ok, I can remove that.

**Comment by mtscout6** [comment]
@AlexKVal I removed that ignore, do you see anything else?

**Comment by AlexKVal** [comment]
Today while I had been trying to untangle `npm run docs` chain,
I've noticed another one https://github.com/react-bootstrap/react-bootstrap/blob/master/webpack/strategies/docs.js#L30, but I'm not sure about it,
because it needs more research for me with your "client-loader".
Maybe you'll learn it faster.

Anyway I would merge this PR already :+1:

**Comment by mtscout6** [comment]
That line is fine, it's still good to tell webpack not to apply loaders to the node_modules folder. That exclude applies to all loaders in the chain not just babel.

**Comment by AlexKVal** [comment]
Eventually I see 3x LGTM and I push `The Big Green Button` :smiling_imp:

**Pull request merged**
