### PR TITLE
[added] bsStyle prop support for Modal to set the header color

### PR DESCRIPTION
**Pull request by stefanfisk**

### CODE REVIEW

**Comment by mtscout6** [comment]
I like the idea of this!

The styling is off though, note the hard corners on the top:



I've bee using [twbs-contextual-modals](https://github.com/binlabs/twbs-contextual-modals) for my project which applies more style to the entire modal, and you can still activate it with `bsStyle='primary'`.

**Comment by stefanfisk** [comment]
Adding overflow: hidden to .modal-content seems to solve it (commited the change), but I don’t have enough time to test it properly right now.

Personally I thing that twbs-contextual-modals goes a bit too far, but to each his own ;)

**Comment by mtscout6** [comment]
Looks good, can you squash your commits for this?

**Comment by stefanfisk** [comment]
Done!

**Comment by stefanfisk** [comment]
Just a sec, the commit message is wrong...

**Comment by stefanfisk** [comment]
There we go.

**Comment by mtscout6** [comment]
Thanks!

**Comment by mtscout6** [comment]
Looks like this caused this bug: #448  @stefanfisk Can you look into this?

**Comment by davidhouweling** [comment]
@mtscout6 @stefanfisk  I believe the correct way to resolve this would be to add a border-top-radius of modal-content + 1 to modal-title. However, there isn't really a clean way to do this across all browsers.

e.g. if modal-content border-top-radius = 6px (default value), the modal-title border-top-radius should be 7px.

**Pull request merged**
