### PR TITLE
Feature/tabs with dropdown

### PR DESCRIPTION
**Pull request by mark2685**
Created example of tabs with dropdown.

Discussion: #100

### CODE REVIEW

**Comment by taion** [comment]
Huh, it looks like this actually doesn't just work – the dropdown tab, while styled correctly, does not properly receive "active" styling. Huh. I wonder if `NavDropdown` should check whether any of its children are active. Probably?

**Comment by jquense** [comment]
probably, that would give it more value as a component anyway. it is a bit annoying to recreate tho if you need to use Dropdown directly in this context... does normal bootstrap handle this correctly?  I don't remember seeing extra code this this (I'll check)

**Comment by taion** [comment]
They special-case it in a way that we can't really here: https://github.com/twbs/bootstrap/blob/master/js/tab.js#L93-L100

**Comment by taion** [comment]
Active state management here is actually completely non-functional. Let's see if there's an easy way to fix.

**Comment by taion** [comment]
Replaced with https://github.com/react-bootstrap/react-bootstrap/pull/2134

**Pull request closed without merging**
