### PR TITLE
Support disabling of DropdownButton.

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by taion** [comment]
We're in the process of a pretty big rewrite of the dropdown-related code. See #1096.

**Comment by tannewt** [comment]
Ok, I'll keep an eye on it and close this if disabling works with
NavDropdown.

**Comment by mtscout6** [comment]
I don't know if I accounted for disabling dropdowns in that PR. If you're up to it you can take a look at it and submit a PR against the dropdown-revisted branch.

**Comment by tannewt** [comment]
Ok. Any idea when it will be merged into master?

**Comment by jquense** [comment]
I believe my most recent commits on the dropdown PR take care of this. 

It'll be merged when its done, no real ETA yet

**Comment by tannewt** [comment]
Sounds good! Thanks!

**Pull request closed without merging**
