### PR TITLE
[changed] Deprecate <Alert dismissAfter>

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
@jquense Thoughts?

**Comment by jquense** [comment]
sorry, LGTM

**Comment by olgeorge** [comment]
I'm wondering why this was deprecated, sounds like a useful feature most of the users would have to reimplement

**Comment by tybro0103** [comment]
If you need a quick fix:

```es6
class DismissAfterAlert extends React.Component {
  componentDidMount() {
    this._timeout = setTimeout(this.props.onDismiss, this.props.dismissAfter);
  }
  componentWillUnmount() {
    clearTimeout(this._timeout);
  }
  render() {
    return <Alert {...this.props} />;
  }
}
```

**Pull request merged**
