### PR TITLE
[added] 'onShow' property to Modal.

### PR DESCRIPTION
**Pull request by codykrainock**
I'm currently building a webapp using react-bootstrap and I am using the Modal class. However, I wanted the ability to pass a callback that would be executed when the modal is shown.

Please review and let me know what you think, it's a rather simple change. Thanks!

### CODE REVIEW

**Comment by taion** [comment]
You could have just re-pushed to the old PR.

Is the concern that the `onEntering` and `onEntered` animation lifecycle hooks are insufficient?

**Comment by codykrainock** [comment]
I wasn't aware that these lifecycle hooks were available since it didn't explicitly say so in the Modal docs - that's what led me to implement `onShow`. Upon further investigation I now see that this exists on the underlying Fade element, which is only used when animation == true.

I think it would be smart to have an `onShow` property simply so that the Modal element isn't tightly coupled to the Fade element. Also, I do feel that the language `onShow` is  much clearer, especially given that the `onHide` prop is available for Modal.

Let me know what your thoughts are.

**Comment by codykrainock** [comment]
I have confirmed through some tests that `onEntering` and `onEntered` are only used when `animation === true`. For this reason I think the `onShow` property would be more sufficient than these lifestyle hooks.

**Comment by taion** [comment]
@jquense 

Any thoughts here? This isn't quite parallel to `onHide`, which does the actual hiding.

I feel that since the developer controls the modal being shown (e.g. by doing `this.setState({shown: true})`) that it's not clear that this adds any new capabilities.

**Comment by jquense** [comment]
I have gone back and forth on this myself...generally an onShow is helpful if you previously had stuff in the `{Wii|Did}Mount` hooks.

However it has been hard to fine something that is a reasonable parallel to `onHide`. At work we settled on adding a hook like:

```js
componentWillMount() {
    if (this.props.onShow && this.props.show)
      this.props.onShow();
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.onShow && nextProps.show && !this.props.show)
      nextProps.onShow();
  }
```

Its been convenient, but it's also easy enough for a user to do themselves. I'd add it if folks don't think it will be confusing that onHide triggers a hide while onShow is an unpreventable hook that's just a convenient alias for checking the `show` prop

**Comment by taion** [comment]
@codykrainock Sorry for letting this languish. I think the right approach here is to let you embed a `ModalDialog` of some form inside a `Modal`, and then use the standard React lifecycle hooks there.

**Comment by codykrainock** [comment]
@taion - thanks for the input. I'll definitely give it a shot!

**Pull request closed without merging**
