### PR TITLE
[fixed] regression when clicking "static" modal backdrops

### PR DESCRIPTION
**Pull request by jquense**
Not sure where this fell to the floor, but clearly we have no tests around it (will get to that)

### CODE REVIEW

**Comment by taion** [comment]
Can you elaborate a bit? It looks like we don't go down this code path at all if `this.props.backdrop` is false: https://github.com/react-bootstrap/react-bootstrap/blob/v0.24.2/src/Modal.js#L183-L185

**Comment by jquense** [comment]
hehe sorry, yeah its not for when its `false` its for when its `"static"`, right now static backdrops are also closing the modal when its clicked.

**Comment by taion** [comment]
Oh, I see. Might want to drop a comment (or explicitly compare to `"static"`) there just to make it more clear what's happening.

**Comment by taion** [comment]
:shipit:

**Pull request merged**
