### PR TITLE
Update for React 0.14.0-rc1 and React Router 1.0.0-rc1

### PR DESCRIPTION
**Pull request by taion**
Going to cut `react-bootstrap@0.25.102-react-pre.0` after this.

### CODE REVIEW

**Comment by AlexKVal** [comment]
I'm not sure if this warning has an importance for update. Could be fixed later o/c. Insignificant.
screen shot 2015-09-13 at 12 09 59 am

Everything seems working. Routing, Components.
LGTM

p.s. `React-0.14` helps to discover some minor errors on the Components page, but they are for another PR o/c
screen shot 2015-09-13 at 12 15 29 am

**Comment by taion** [comment]
I didn't see that error. Will take a look.

**Comment by AlexKVal** [comment]
I've rechecked:
```
> git checkout pr/1319
> rm -rf node_modules && npm i
> npm run docs
> open http://localhost:4000/components.html
```
there are all those warnings in the dev. console.
Full page reload - and they are still exist.

**Comment by taion** [comment]
I'm seeing a mismatch between

(server)
```html
<button id="bg-vertical-dropdown-1" class="dropdown-toggle btn btn-default" type="button" aria-haspopup="true" aria-expanded="false" data-reactid=".22v56e0purk.1.0.2.0.0.1.h.0.0.0.2.$/=10">
```

and

(client)
```html
<button aria-expanded="false" aria-haspopup="true" class="dropdown-toggle btn btn-default" type="button" id="bg-vertical-dropdown-1" data-reactid=".22v56e0purk.1.0.2.0.0.1.h.0.0.0.2.$/=10">
```

This is really weird but I don't think it's a blocker, so I'm going to release.

**Comment by jquense** [comment]
Do we think this may be a react bug? worth mentioning it their issue tracker?

**Comment by taion** [comment]
The really weird thing is that it's not consistently reproducible. This only seems to happen the first time I hit that page, but not the second. I don't know.

**Comment by AlexKVal** [comment]
Yeah.. After you had mentioned this, I've noticed it too:
it is not consistently reproducible indeed. Some weird subtle bug :smile:

**Pull request merged**
