### PR TITLE
Fix <OverlayTrigger> rootClose regression

### LINKED ISSUE #233: Popover dismiss on next click
I've been trying to figure out how to get the popover to close when you click anywhere outside of it. Tried using the markup from the bootstrap documentation (use href with tabindex=0) but looking through the code, it doesn't seem it's handled anywhere. Am I missing something?

### PR DESCRIPTION
**Pull request by taion**
Fixes #233

Requires #2095 for clean build

### CODE REVIEW

**Comment by jquense** [comment]
I'm surprised a test didn't already catch this!

**Comment by jquense** [comment]
LGTM tho

**Comment by taion** [comment]
We didn't have any test coverage for the case of clicking on the trigger when `rootClose` was enabled.

**Comment by taion** [comment]
Still don't know why we wrote `rootClose` that way.

**Pull request merged**
