### PR TITLE
Be more consistent with subcomponents

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by jquense** [comment]
LGTM

**Comment by taion** [comment]
We're not particularly consistent about top-level exports here, though.

**Comment by jquense** [comment]
Yeah at this point maybe we do one big break and remove sub components from the top export?

**Comment by taion** [comment]
I'd be okay with that. It's really weird that some of them are available but some aren't right now.

**Comment by jquense** [comment]
I agree, I take it neither of us import the top level RB ever.

**Comment by taion** [comment]
At some point I'd like to move to top-level imports, once webpack 2 is really out and stable and we have an ES module build.

**Pull request merged**
