### PR TITLE
FormControl should accept `xs` as bsSize

### PR DESCRIPTION
**Pull request by Liooo**
right?

### CODE REVIEW

**Comment by taion** [comment]
Well, we pass it down to the input, and there is no `.input-xs`.

**Comment by Liooo** [comment]
@taion Absolutely. 

Sorry, forgot `.input-xs` was defined manually and was used in my app. Sorry for bothering.

**Comment by taion** [comment]
I forget... can we update the prop types to add new supported sizes?

**Comment by Liooo** [comment]
@taion sorry I didn't understand, what's new supported sizes?

**Comment by taion** [comment]
@Liooo Use `bsSizes` from `bootstrapUtils` to add `xs` as a supported `bsSize`.

**Comment by Liooo** [comment]
But `.input-xs` isn't supported officially by bootstrap as you have pointed out

**Pull request closed without merging**
