### PR TITLE
use RCW disabled to avoid unnecessary unmount

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
can we kill this version eye thing??

**Comment by taion** [comment]
I deleted the web hook... let's see if that works.

**Comment by saxicek** [comment]
This change broke preact compatibility. Not sure why but 0.30.3 DropdownMenu works in preact while 0.30.4 does not.

**Comment by taion** [comment]
0.30.4 is broken; it was untagged and the current release is 0.30.5.

**Comment by ngduc** [comment]
@saxicek just curious if the latest version works with Preact?

**Comment by saxicek** [comment]
@ngduc Tested with react-bootstrap@0.30.7, preact@7.1.0 and preact-compat@3.13.0 and it still does not work. Also tried with 0.30.3 which does not work either so now I am not sure what causes the issue.

My test is described at https://github.com/developit/preact-compat/issues/146 if you want to replicate and dive deeper.

**Comment by jquense** [comment]
this definitely works with React, because we have behavior depending on the components saying mounted. Not sure about Preact, but there isn't much we can do on that front.

**Comment by saxicek** [comment]
Yes, I can confirm it works with React. I was only discussing preact-compat compatibility where dropdown menu does not work.

**Comment by jquense** [comment]
sure :) just wanted to add that i don't think we had a regression somewhere, so soundly in Preacts compat layer

**Pull request merged**
