### PR TITLE
Fix ES module build

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by jharris4** [comment]
@taion @jquense Was this PR intended to be merged before `0.31.4` was released and it just got missed?

**Comment by shayja** [comment]
Hi, same error for me too after upgrading to 0.31.4

ReferenceError: exports is not defined

 84 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  85 | 		hotCurrentParents = [];
  86 | 	}
> 87 | 	return __webpack_require__(request);
  88 | };
  89 | var ObjectFactory = function ObjectFactory(name) {
  90 | 	return {
View compiled
./src/components/Layout/NavigationBar.js

**Comment by taion** [comment]
@jharris4 This is to correct a mistake in https://github.com/react-bootstrap/react-bootstrap/pull/2837, which was to correct another issue that was breaking the ES build entirely. I mean, the bug here also breaks the ES build, but differently.

**Comment by jharris4** [comment]
Hmm not sure I follow, but 0.31.4 is currently fairly busted... :-(

**Comment by jharris4** [comment]
@taion have you seen #2860 (with duplicates as #2858 and #2859) ?

**Comment by taion** [comment]
We'll publish the new version shortly.

**Comment by jharris4** [comment]
@taion awesome! And thanks for all your hard work on this project, much appreciated;-)

**Comment by taion** [comment]
I'm just going to merge this as a trivial fix.

**Comment by shayja** [comment]
Thanks,
updated to react-bootstrap@0.31.5 fixed my problem

**Comment by andpor** [comment]
0.31.5 creates a build issue . 

`Module not found: Error: Cannot resolve module 'react-prop-types/lib/isRequiredForA11y`

**Pull request merged**
