### PR TITLE
Updated documentation with multiple expandable Panels.

### PR DESCRIPTION
**Pull request by gfunk1230**
In regards to my old PR https://github.com/react-bootstrap/react-bootstrap/pull/2775

Example:

react-bootstrap-multipanel-docs

### CODE REVIEW

**Comment by jquense** [comment]
many thanks!

**Comment by rovolution** [comment]
🎉

**Comment by rovolution** [comment]
@jquense are you able to deploy this change to the docs page? Thanks!

**Comment by taion** [comment]
I'll cut a release.

**Pull request merged**
