### PR TITLE
Modal & Portal code style cleanup to match rest of project.

### PR DESCRIPTION
**Pull request by hedgerh**
A few code style cleanups to get the Modal and Portal components to match the rest of the codebase.

This is my first PR, so let me know if I'm doing anything wrong.  Thanks!

### CODE REVIEW

**Comment by AlexKVal** [comment]
Hi :smiley: 
Thank you for your attention and your wish to contribute to this project :+1: :sparkle: 

Just a hint about `GitHub` PR's:
you don't have to close your "spoiled" PRs like this https://github.com/react-bootstrap/react-bootstrap/pull/1123.
You can just push forced changes into it - it's OK.
Like this:
```sh
> ... you re-wrote your code after you made PR
> git add ... as usual
> git commit ... as usual
> git push --forced // <- that is the key: `--forced` will just overwrite 
your old "bad"/"wrong" commit's code
```
And that's all :wink: 

--
As for your stylistic changes of the code.
This project is not too strict to styles. Just a couple of rules:
https://github.com/react-bootstrap/react-bootstrap/blob/master/.eslintrc

The main idea is to have `more or less` consistent style and in the same time
to `not impede` new possible collaborators by too strict specifications :sparkle: 

--
I must share - I began almost the same way in this project :smile:. 
But there were too many eslint warnings and I was happy to kill them one by one :smile: 
https://github.com/react-bootstrap/react-bootstrap/pull/485

--
@jquense (one of the Owners of this project) is already well aware of `his own style` vs `semi-style` of this project :smile: 
You are trying to fix 90% exactly of his code :smile:

Jokes aside: Your wish to contribute is praiseworthy :cherries: 
You definitely could help more if you deal with any of [bugs](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) or [help wanted](https://github.com/react-bootstrap/react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+) issues :+1:

**Comment by AlexKVal** [comment]
I must apologize, I said a lot and I said nothing about your PR :blush: 

It looks good to me. :sparkle: 
Though I'm not the owner and I'm not sure what do they think about such kind
of pull requests (purely stylistic changes).
(personally I don't see at least any harm in it) :cherries: 

Anyway it needs at least one more approval from @react-bootstrap/collaborators

**Comment by hedgerh** [comment]
hi @AlexKVal, thanks for your response.  i know code style PRs are a bit silly.  while working with the modal components on a project, i saw that there were some style things that were inconsistent within the same files, as well as the project as a whole.  i figured those were worth touching up.  while i was at it, i threw in a couple of the more trivial ones as well.

thanks for the advice.  im going to see if i can take on any of the open issues.  i figured this would be a nice way to test the waters. :octopus:

**Comment by AlexKVal** [comment]
>  i figured this would be a nice way to test the waters. :octopus:

I did the same :smile: :+1:

**Comment by jquense** [comment]
Thanks, @hedgerh for taking the time to help out. In the future i wouldn't worry to much about correcting style beyond lint warning/errors, just because any amount of refactoring may accidentally introduce a subtle bug.

In this case though i'd be happy to accept and merge your first PR :)

**Comment by taion** [comment]
We could add ESLint rules for code style though :D

**Pull request merged**
