### PR TITLE
Dom utils

### PR DESCRIPTION
**Pull request by jquense**
beginning prep work for swapping out overlay stuff with react-overlays. Removes our dom helpers and uses dom-helpers so both packages can share the same helpers. Bonus, we finally remove our jquery dependency for ie8.

Slightly unrelated I removed domUtils from the public API, why where they there in the first place? If folks would like a deprecation we could do that, tho I think it would be cleaner just to point ppl to dom-helpers if they need those utils. In either case i seemed weird to me for RB have them as a part of a public api

### CODE REVIEW

**Comment by taion** [comment]
For history there see:

https://github.com/react-bootstrap/react-bootstrap/issues/743
https://github.com/react-bootstrap/react-bootstrap/pull/745
https://github.com/react-bootstrap/react-bootstrap/pull/768

Moving them into separate packages is a much better way to go, though.

/cc @tomatau

**Comment by AlexKVal** [comment]
If we are removing [domUtils](https://github.com/react-bootstrap/react-bootstrap/pull/1172/files#diff-1fdf421c05c1140f6d71444ea2b27638L82) without transitional deprecation warning,
then I propose to do the same with `CustomPropTypes`. https://github.com/react-bootstrap/react-bootstrap/pull/1063

And also remove them in favor of https://github.com/react-bootstrap/react-prop-types `npm package`

**Comment by jquense** [comment]
I don't mind adding a deprecation warning, just wondering if it makes sense too. I do think we should do the same thing for propTypes tho :)

**Comment by AlexKVal** [comment]
I have `react-prop-types` local branch prepared to PR after `v0.25`,
but if we decide to proceed w/o transitional deprecation warning, I will PR them against the `v0.25` branch.

**Comment by taion** [comment]
LGTM other than that one comment about the docs webpack config... just want to understand what it's for.

**Comment by AlexKVal** [comment]
@taion should I PR my local branch for https://github.com/react-bootstrap/react-bootstrap/issues/937 against `v0.25-rc` then (instead of `26`) ?
(https://github.com/react-bootstrap/react-bootstrap/pull/1172#issuecomment-131823637)

**Comment by taion** [comment]
@jquense This is good to merge after we strip the docs Webpack config changes.

@AlexKVal Let's keep it with the deprecation warning for now.

**Comment by AlexKVal** [comment]
@taion OK. No problem. :cherries:

**Pull request merged**
