### PR TITLE
Add documentation on support and issues

### PR DESCRIPTION
**Pull request by mtscout6**
We regularly encounter issues that we cannot verify, primarily due to issue authors not responding to our questions for clarity. This proposes a timeline we can all follow to know when it's a good time to close the
issue on our end.

Some of the documentation I acquired from [bootstrap's CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md). I really like a lot of what they have in there and if I get more time in the future I may borrow more of what they have.

### CODE REVIEW

**Comment by AlexKVal** [comment]
We are lucky enough to not having such expirience so far:
> Please do not derail or troll issues.

IMHO I woudn't add it. 
(at least till we really get such a bad experience and even in that case
we got moderator rights and will always remove any inappropriate posts!)
"don't call the devil" :cherries: 

This phrase I am (as a foreigner) totally do not understand:
> regarding the code in Normalize

I would simplify that line also.

Everything other is :+1:

**Comment by mtscout6** [comment]
Ah, that was from Bootstrap when I copied it, I'll remove that Normalize jargon

**Comment by AlexKVal** [comment]
I propose to remove the "or troll" part.
It is a negative word.

I may only tell from my personal experience...
If I read in any project negative words or phrases, or there is too much commanding tone...
(I mean of course OSS projects)
I don't like this project.. I pass by.. I ignore it.. 
Because I don't like `the negative` in any form. Even in an allusion form.

That' my User Experience.

P.S. Of course I won't 'pass by' this R-B project :smile: already, because I'm involved in it too much already :stuck_out_tongue_closed_eyes:

**Comment by mtscout6** [comment]
@AlexKVal I cut it out

**Comment by AlexKVal** [comment]
Thank you :cherries: :smile: 

7 days :+1: 

LGTM

**Comment by dozoisch** [comment]
LGTM! 7 days perfect I think

**Comment by mtscout6** [comment]
Felt if was good to encompass our weekend warriors

**Pull request merged**
