### PR TITLE
WIP: Adding Info to Landing Page

### PR DESCRIPTION
**Pull request by ejachang**
Added some info on the landing page about react v. react-bootstrap differences for[ issue #3043](https://github.com/react-bootstrap/react-bootstrap/issues/3043):
- Differences between component style
- How each interacts with DOM
- A little info on state

I had a few notes/questions:
1. I was wondering if it be fine to include markup on the landing page? I think it would be nice to illustrate the differences between react-bootstrap and bootstrap. If so, is there a preferred way for markup to be incorporated for these pages? I noticed MDX is being used for the other pages. 
2. I'm still working on the formatting - not sure if it is ok the way it is or not.
3. Other than this additional info and possibly adding markup to illustrate the differences, I've actually been a little lost about what else to add for the non-API pages.  I've still been trying to think of what else to add, but are there any specifics that come to mind?
4. Kind of nit-picky, but should React-Bootstrap be written as "React-Bootstrap" throughout the pages? I noticed there were variations in v4 and wasn't sure if the mechanics changed.
5. I'm not sure if what I added is better on landing page or "Getting Started/Introduction”. Let me know and I’ll move it.

### CODE REVIEW

**Comment by jquense** [comment]
phew sorry for the complete lack of a response here. We've been all in a bit of hole doing non OSS stuff. This looks good, I think we need to clean up the copy a bit but seems like an improvement 👍 

> I was wondering if it be fine to include markup on the landing page?

Absolutely, we `mdx` in particular lets you put any amount of react logic right in the markdown

> Other than this additional info and possibly adding markup to illustrate the differences, I've actually been a little lost about what else to add for the non-API pages. I've still been trying to think of what else to add, but are there any specifics that come to mind?

We've been deferring a lot to the upstream bootstrap docs in places since they are pretty comprehensive. I do think it's probably good to have some "common setups" things, like https://github.com/react-bootstrap/react-bootstrap/pull/3377 specifically to just answer some questions about how to do stuff, or explain our logic on this. That said i can't think of a lot of things we are missing

> I'm not sure if what I added is better on landing page or "Getting Started/Introduction”. Let me know and I’ll move it.

I think it's good here but we probably want to add some visual distance from the top landing bit

**Comment by bpas247** [comment]
@ejachang Any chance this PR will move out of `WIP` status anytime soon?

**Comment by ejachang** [comment]
@bpas247 sorry for the delay! Aiming to move out by EOM.

**Comment by ejachang** [comment]
@bpas247 Sorry for the delay again - took longer than I thought. I wanted let you know I'm almost done with moving this out of WIP status and hoping to do so by the end of this week

**Comment by ejachang** [comment]
@jquense  @bpas247 This is really embarrassing, but something went wrong on my local branch and pushing it, which very obviously affected to this PR. I'll work on fixing and creating a new PR for this soon. Sorry about this!

**Comment by jquense** [comment]
np @ejachang take your time

**Comment by ejachang** [comment]
@jquense To clarify - should the PR for this issue be off of the v4-support branch or master? Thanks!

**Comment by taion** [comment]
The `v4-support` branch is defunct now. It should just be `master`.

**Pull request closed without merging**
