### PR TITLE
Add Introduction page to docs, explaining project

### PR DESCRIPTION
**Pull request by syllog1sm**
Edit: I've revised the text at introduction.html, scrapped the changes I was proposing to Getting Started, and now suggest a button group of links on the homepage.

I've pushed a demo to my gh-pages, but the gh-pages version is a bit broken (the production version looks okay --- this gh-pages version is just so you can view the pages easily.)

https://syllog1sm.github.io/react-bootstrap/introduction.html
https://syllog1sm.github.com/react-bootstrap/

### CODE REVIEW

**Comment by AlexKVal** [comment]
@syllog1sm could you please 
- [ ] remove all but `docs/src/IntroductionPage.js` file
- [ ] then squash all commits into one

Then I'll be able to do:
- [ ] merge it into the project (just as `docs/src/IntroductionPage.js` file. no navigations)
- [ ] fix wording and examples
- [ ] add navigations to be published with docs

**Comment by dozoisch** [comment]
@AlexKVal at this point, I think we can just cherrypick the intro page commit and build a new pr

**Comment by AlexKVal** [comment]
This PR I'm closing if favor of successor #619.

**Comment by AlexKVal** [comment]
IntroPage has been merged.
Thank you @syllog1sm :sparkles:

**Pull request closed without merging**
